/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import dao.DichVuPhongDao;
import dao.HoaDonChiTietDao;
import dao.HoaDonDao;
import dao.PhongDao;
import helper.Auth;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.StyleConstants.ColorConstants;
import model.DichVuPhong;
import model.HoaDon;
import model.HoaDonChiTiet;
import model.Phong;

/**
 *
 * @author Admin
 */
public final class HoaDonWindows extends javax.swing.JPanel {

    /**
     * Creates new form Nha
     */
    public HoaDonWindows() {
        initComponents();
        cboThang.setSelectedIndex(11);
        cboNam.setSelectedIndex(1);
        if (Auth.user.isRoles() == false) {
            pnl_Loc.setVisible(false);
            pnlMenu.setVisible(false);
            btnLuuChiSo.setVisible(false);
            fillToHoaDonKhachThue();
        } else {
            fillToHoaDon();
            fillcboChonPhong();
            moi();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        pnlContent = new javax.swing.JTabbedPane();
        pnlDanhSachHoaDon = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDanhSachHoaDon = new javax.swing.JTable();
        pnl_Loc = new javax.swing.JPanel();
        lblThang = new javax.swing.JLabel();
        cboThang = new javax.swing.JComboBox<>();
        lblNam = new javax.swing.JLabel();
        cboNam = new javax.swing.JComboBox<>();
        cboTrangThai = new javax.swing.JComboBox<>();
        lblTrangThai = new javax.swing.JLabel();
        pnlChiTietHoaDon = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSoNuocCu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSoDienMoi = new javax.swing.JTextField();
        txtSoDienCu = new javax.swing.JTextField();
        txtSoNuocMoi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSoDienSuDung = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSoNuocSuDung = new javax.swing.JTextField();
        lblTienPhong = new javax.swing.JLabel();
        btnLuuChiSo = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        pnlChonPhong = new javax.swing.JPanel();
        lblConPhong = new javax.swing.JLabel();
        cboPhong = new javax.swing.JComboBox<>();
        lblPhong = new javax.swing.JLabel();
        lblThangNam = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        rdoDaThanhToan = new javax.swing.JRadioButton();
        rdoChuaThanhToan = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChiTietHoaDon = new javax.swing.JTable();
        pnlMenu = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnIn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblSoToaNha2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1030, 710));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlContent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pnlDanhSachHoaDon.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tblDanhSachHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Nhà", "Phòng", "Tháng-Năm", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSachHoaDon.setGridColor(new java.awt.Color(204, 204, 204));
        tblDanhSachHoaDon.setRowHeight(30);
        tblDanhSachHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachHoaDonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDanhSachHoaDon);

        pnl_Loc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lblThang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblThang.setText("Tháng:");

        cboThang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        cboThang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboThangItemStateChanged(evt);
            }
        });

        lblNam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNam.setText("Năm:");

        cboNam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        cboNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNamActionPerformed(evt);
            }
        });

        cboTrangThai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đã thanh toán", "Chưa thanh toán" }));
        cboTrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTrangThaiActionPerformed(evt);
            }
        });

        lblTrangThai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTrangThai.setText("Trạng thái hóa đơn");

        javax.swing.GroupLayout pnl_LocLayout = new javax.swing.GroupLayout(pnl_Loc);
        pnl_Loc.setLayout(pnl_LocLayout);
        pnl_LocLayout.setHorizontalGroup(
            pnl_LocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LocLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblThang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboThang, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboNam, 0, 95, Short.MAX_VALUE)
                .addGap(34, 34, 34)
                .addComponent(lblTrangThai)
                .addGap(18, 18, 18)
                .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );
        pnl_LocLayout.setVerticalGroup(
            pnl_LocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_LocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_LocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_LocLayout.createSequentialGroup()
                        .addGroup(pnl_LocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_LocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cboNam)
                                .addComponent(lblNam))
                            .addGroup(pnl_LocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cboThang)
                                .addComponent(lblThang)))
                        .addGap(56, 56, 56))
                    .addGroup(pnl_LocLayout.createSequentialGroup()
                        .addGroup(pnl_LocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_LocLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout pnlDanhSachHoaDonLayout = new javax.swing.GroupLayout(pnlDanhSachHoaDon);
        pnlDanhSachHoaDon.setLayout(pnlDanhSachHoaDonLayout);
        pnlDanhSachHoaDonLayout.setHorizontalGroup(
            pnlDanhSachHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhSachHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDanhSachHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_Loc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        pnlDanhSachHoaDonLayout.setVerticalGroup(
            pnlDanhSachHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhSachHoaDonLayout.createSequentialGroup()
                .addComponent(pnl_Loc, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlContent.addTab("Danh sách hóa đơn", pnlDanhSachHoaDon);

        pnlChiTietHoaDon.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Chỉ số điện:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Chỉ số nước:");

        txtSoNuocCu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Số cũ:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Số mới");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Số cũ:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Số mới");

        txtSoDienMoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtSoDienCu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtSoNuocMoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Tổng");

        txtSoDienSuDung.setEditable(false);
        txtSoDienSuDung.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Tổng");

        txtSoNuocSuDung.setEditable(false);
        txtSoNuocSuDung.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblTienPhong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTienPhong.setText("Tiền phòng:");

        btnLuuChiSo.setText("Lưu chỉ số");
        btnLuuChiSo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuChiSoActionPerformed(evt);
            }
        });

        jPanel8.setLayout(new java.awt.CardLayout());

        pnlChonPhong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblConPhong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblConPhong.setText("Chọn phòng");
        pnlChonPhong.add(lblConPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        cboPhong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboPhong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboPhongItemStateChanged(evt);
            }
        });
        cboPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboPhongMouseClicked(evt);
            }
        });
        pnlChonPhong.add(cboPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 0, 330, 40));

        jPanel8.add(pnlChonPhong, "card2");

        lblPhong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblPhong.setText("PHÒNG");
        jPanel8.add(lblPhong, "card3");

        lblThangNam.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblThangNam.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThangNam.setText("Hóa đơn tháng");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblThangNam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLuuChiSo)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSoNuocCu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSoNuocMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSoNuocSuDung, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addComponent(txtSoDienCu, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(74, 74, 74))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addComponent(txtSoDienMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtSoDienSuDung, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblTienPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 201, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(lblThangNam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTienPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtSoDienCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoDienMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoDienSuDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtSoNuocCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtSoNuocMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(txtSoNuocSuDung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(btnLuuChiSo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Trạng thái:");

        buttonGroup1.add(rdoDaThanhToan);
        rdoDaThanhToan.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        rdoDaThanhToan.setText("Đã thanh toán");

        buttonGroup1.add(rdoChuaThanhToan);
        rdoChuaThanhToan.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        rdoChuaThanhToan.setText("Chưa thanh toán");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Các khoản thu");

        lblTongTien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTongTien.setText("Tổng tiền hóa đơn:");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tblChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Khoản thu", "Số cũ", "Số mới", "Sử dụng", "Giá", "Thành tiền"
            }
        ));
        tblChiTietHoaDon.setGridColor(new java.awt.Color(204, 204, 204));
        tblChiTietHoaDon.setRowHeight(30);
        jScrollPane1.setViewportView(tblChiTietHoaDon);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(rdoDaThanhToan)
                                .addGap(18, 18, 18)
                                .addComponent(rdoChuaThanhToan))
                            .addComponent(lblTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rdoDaThanhToan)
                    .addComponent(rdoChuaThanhToan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));
        pnlMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        pnlMenu.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 121, 39));

        btnCapNhat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        pnlMenu.add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 121, 39));

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        pnlMenu.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 117, 39));

        btnMoi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        pnlMenu.add(btnMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 121, 39));

        btnIn.setText("In hóa đơn PDF");
        btnIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInActionPerformed(evt);
            }
        });
        pnlMenu.add(btnIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, 39));

        javax.swing.GroupLayout pnlChiTietHoaDonLayout = new javax.swing.GroupLayout(pnlChiTietHoaDon);
        pnlChiTietHoaDon.setLayout(pnlChiTietHoaDonLayout);
        pnlChiTietHoaDonLayout.setHorizontalGroup(
            pnlChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChiTietHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlChiTietHoaDonLayout.createSequentialGroup()
                        .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlChiTietHoaDonLayout.setVerticalGroup(
            pnlChiTietHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChiTietHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 262, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlContent.addTab("Chi tiết hóa đơn", pnlChiTietHoaDon);

        jPanel3.setBackground(new java.awt.Color(40, 63, 85));
        jPanel3.setPreferredSize(new java.awt.Dimension(139, 62));

        lblSoToaNha2.setBackground(new java.awt.Color(255, 255, 255));
        lblSoToaNha2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSoToaNha2.setForeground(new java.awt.Color(255, 255, 255));
        lblSoToaNha2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoToaNha2.setText("Hóa đơn");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSoToaNha2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSoToaNha2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1008, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlContent)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblDanhSachHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachHoaDonMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            indexHoaDon = tblDanhSachHoaDon.getSelectedRow();
            clickTableHoaDon();
            pnlContent.setSelectedIndex(1);
        }
    }//GEN-LAST:event_tblDanhSachHoaDonMouseClicked

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        moi();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void cboPhongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboPhongItemStateChanged
        // TODO add your handling code here:
        showInsert();
    }//GEN-LAST:event_cboPhongItemStateChanged

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        insertHD();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnLuuChiSoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuChiSoActionPerformed
        // TODO add your handling code here:
        luuChiTiet();
    }//GEN-LAST:event_btnLuuChiSoActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void cboPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboPhongMouseClicked

    }//GEN-LAST:event_cboPhongMouseClicked

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        update();
        fillToHoaDon();
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInActionPerformed
        // TODO add your handling code here:
        printPDF();
    }//GEN-LAST:event_btnInActionPerformed

    private void cboThangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboThangItemStateChanged
        // TODO add your handling code here:
        fillToHoaDon();
    }//GEN-LAST:event_cboThangItemStateChanged

    private void cboNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNamActionPerformed
        // TODO add your handling code here:
        fillToHoaDon();
    }//GEN-LAST:event_cboNamActionPerformed

    private void cboTrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTrangThaiActionPerformed
        // TODO add your handling code here:
        fillToHoaDon();
    }//GEN-LAST:event_cboTrangThaiActionPerformed

    //start code
    HoaDonDao hdDao = new HoaDonDao();

    public void fillToHoaDon() {
        int thang = Integer.parseInt(cboThang.getSelectedItem() + "");
        int nam = Integer.parseInt(cboNam.getSelectedItem() + "");
        boolean trangthai;
        trangthai = cboTrangThai.getSelectedItem() == "Đã thanh toán";
        List<HoaDon> list = hdDao.selectByCbo(thang, nam, trangthai);
        DefaultTableModel model = (DefaultTableModel) tblDanhSachHoaDon.getModel();
        model.setRowCount(0);
        for (HoaDon h : list) {
            Object[] row = new Object[]{h.getIdHoaDon(), h.getTenToaNha(), h.getTenPong(), h.getThang() + "-" + h.getNam(), h.isTrangThai() == true ? "Đã thanh toán " : "Chưa thanh toán"};
            model.addRow(row);
        }
    }

    public void fillToHoaDonKhachThue() {
        List<HoaDon> list = hdDao.selectByKhachThue(Auth.user.getIdkhachthue());
        DefaultTableModel model = (DefaultTableModel) tblDanhSachHoaDon.getModel();
        model.setRowCount(0);
        for (HoaDon h : list) {
            Object[] row = new Object[]{h.getIdHoaDon(), h.getTenToaNha(), h.getTenPong(), h.getThang() + "-" + h.getNam(), h.isTrangThai() == true ? "Đã thanh toán " : "Chưa thanh toán"};
            model.addRow(row);
        }
    }
    int indexHoaDon;
    int idHoaDon;

    HoaDonChiTietDao hdctDao = new HoaDonChiTietDao();

    public void clickTableHoaDon() {
        idHoaDon = Integer.parseInt(tblDanhSachHoaDon.getValueAt(indexHoaDon, 0) + "");
        List<HoaDonChiTiet> list = hdctDao.selectByIDHoaDon(idHoaDon);
        DefaultTableModel model = (DefaultTableModel) tblChiTietHoaDon.getModel();
        model.setRowCount(0);
        for (HoaDonChiTiet x : list) {
            System.out.println(x.getKhoanThu());
            if (x.getKhoanThu().equals("Nước")) {
                txtSoNuocCu.setText(x.getSoCu() + "");
                txtSoNuocMoi.setText(x.getSoMoi() + "");
                txtSoNuocSuDung.setText(x.getSuDung() + "");
            }
            if (x.getKhoanThu().equals("Điện")) {
                txtSoDienCu.setText(x.getSoCu() + "");
                txtSoDienMoi.setText(x.getSoMoi() + "");
                txtSoDienSuDung.setText(x.getSuDung() + "");
            }
            Object[] o = new Object[]{x.getKhoanThu(), x.getSoCu(), x.getSoMoi(), x.getSuDung(), x.getGia(), x.getSuDung() * x.getGia()};
            model.addRow(o);
        }
        double tongTien = 0;
        for (int i = 0; i <= tblChiTietHoaDon.getRowCount() - 1; i++) {
            tongTien = tongTien + Double.parseDouble(tblChiTietHoaDon.getValueAt(i, 5) + "");
        }
        lblTongTien.setText("Tổng tiền: " + tongTien + "");
        HoaDon h = hdDao.selectByID(idHoaDon);
        rdoDaThanhToan.setSelected(h.isTrangThai());
        rdoChuaThanhToan.setSelected(!h.isTrangThai());
        setStatus(false);
        lblPhong.setText("Phòng: " + tblDanhSachHoaDon.getValueAt(indexHoaDon, 2) + "-" + tblDanhSachHoaDon.getValueAt(indexHoaDon, 1));
        lblThangNam.setText("Hóa đơn tháng " + tblDanhSachHoaDon.getValueAt(indexHoaDon, 3));
        if (h.isTrangThai() == true) {
            btnCapNhat.setEnabled(false);
            txtSoDienCu.setEditable(false);
            txtSoDienMoi.setEditable(false);
            txtSoNuocCu.setEditable(false);
            txtSoNuocMoi.setEditable(false);
        }
    }
    PhongDao pDao = new PhongDao();

    public void fillcboChonPhong() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboPhong.getModel();
        model.removeAllElements();
        List<Phong> list = pDao.selectByHoaDon(new Date().getMonth() + 1, new Date().getYear() + 1900);
        for (Phong p : list) {
            model.addElement(p);
        }

    }

    public void moi() {
        txtSoDienCu.setText("");
        txtSoDienMoi.setText("");
        txtSoNuocCu.setText("");
        txtSoNuocMoi.setText("");
        txtSoDienSuDung.setText("");
        txtSoNuocSuDung.setText("");
        lblTongTien.setText("Tổng tiền:...");
        rdoChuaThanhToan.setSelected(true);
        DefaultTableModel model = (DefaultTableModel) tblChiTietHoaDon.getModel();
        model.setRowCount(0);
        setStatus(true);
        try {
            cboPhong.setSelectedIndex(0);
        } catch (Exception e) {
            DefaultComboBoxModel modelcbo = (DefaultComboBoxModel) cboPhong.getModel();
            modelcbo.addElement("Đã tạo hết các hóa đơn cho tháng này");
        }
        lblThangNam.setText("Tạo hóa đơn tháng " + (new Date().getMonth() + 1) + " năm " + (new Date().getYear() + 1900));
    }
    DichVuPhongDao dvpDao = new DichVuPhongDao();
    int idPhong;

    public void showInsert() {
        try {
            idPhong = ((Phong) cboPhong.getSelectedItem()).getIdphong();
            Phong p = pDao.selectByID(idPhong);
            lblTienPhong.setText("Tiền phòng: " + p.getGia() + "");
            rdoChuaThanhToan.setSelected(true);
        } catch (Exception e) {
        }
    }

    public void luuChiTiet() {
        try {
            idPhong = ((Phong) cboPhong.getSelectedItem()).getIdphong();
        } catch (Exception e) {
        }
        Phong p = pDao.selectByID(idPhong);
        DefaultTableModel model = (DefaultTableModel) tblChiTietHoaDon.getModel();
        model.setRowCount(0);
        List<DichVuPhong> list = dvpDao.selectByIDPhong(idPhong);
        Object[] tienPhong = new Object[]{"Tiền Phòng", 0, 0, 1, p.getGia(), p.getGia()};
        model.addRow(tienPhong);
        txtSoDienSuDung.setText((Integer.parseInt(txtSoDienMoi.getText()) - Integer.parseInt(txtSoDienCu.getText())) + "");
        txtSoNuocSuDung.setText((Integer.parseInt(txtSoNuocMoi.getText()) - Integer.parseInt(txtSoNuocCu.getText())) + "");
        for (DichVuPhong d : list) {
            if (d.getTenDichVu().equals("Điện")) {
                Object[] row = new Object[]{"Điện", txtSoDienCu.getText(), txtSoDienMoi.getText(), txtSoDienSuDung.getText(), d.getGia(), (Integer.parseInt(txtSoDienSuDung.getText())) * d.getGia()};
                model.addRow(row);
            } else if (d.getTenDichVu().equals("Nước")) {
                Object[] row = new Object[]{"Nước", txtSoNuocCu.getText(), txtSoNuocMoi.getText(), txtSoNuocSuDung.getText(), d.getGia(), (Integer.parseInt(txtSoNuocSuDung.getText())) * d.getGia()};
                model.addRow(row);
            } else {
                Object[] row = new Object[]{d.getTenDichVu(), 0, 0, d.getSoLuong(), d.getGia(), d.getSoLuong() * d.getGia()};
                model.addRow(row);
            }
        }
        double tongTien = 0;
        for (int i = 0; i <= tblChiTietHoaDon.getRowCount() - 1; i++) {
            tongTien = tongTien + Double.parseDouble(tblChiTietHoaDon.getValueAt(i, 5) + "");
        }
        lblTongTien.setText("Tổng tiền: " + tongTien + "");
    }

    public void insertHD() {
        HoaDon h = new HoaDon(0, idPhong, new Date().getMonth() + 1, new Date().getYear() + 1900, false);
        System.out.println(h);
        hdDao.insert(h);
        fillToHoaDon();
        insertHDCT();
        JOptionPane.showMessageDialog(this, "Đã thêm");
        moi();
        fillcboChonPhong();
    }

    public void insertHDCT() {
        try {
            List<HoaDon> list = hdDao.selectAll();
            HoaDon hd = list.get(list.size()-1);
            int idHD = hd.getIdHoaDon();
            for (int i = 0; i <= tblChiTietHoaDon.getRowCount() - 1; i++) {
                HoaDonChiTiet hdct = new HoaDonChiTiet();
                hdct.setIdHoaDon(idHD);
                hdct.setKhoanThu(tblChiTietHoaDon.getValueAt(i, 0) + "");
                hdct.setSoCu(Integer.parseInt(tblChiTietHoaDon.getValueAt(i, 1) + ""));
                hdct.setSoMoi(Integer.parseInt(tblChiTietHoaDon.getValueAt(i, 2) + ""));
                hdct.setSuDung(Integer.parseInt(tblChiTietHoaDon.getValueAt(i, 3) + ""));
                hdct.setGia(Double.parseDouble(tblChiTietHoaDon.getValueAt(i, 4) + ""));
                hdctDao.insert(hdct);

            }
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Nhập lại chỉ số điện nước");
        }
    }

    public void update() {
        try {
            for (int i = 0; i <= tblChiTietHoaDon.getRowCount() - 1; i++) {
                HoaDonChiTiet hdct = new HoaDonChiTiet();
                hdct.setIdHoaDon(idHoaDon);
                hdct.setKhoanThu(tblChiTietHoaDon.getValueAt(i, 0) + "");
                hdct.setSoCu(Integer.parseInt(tblChiTietHoaDon.getValueAt(i, 1) + ""));
                hdct.setSoMoi(Integer.parseInt(tblChiTietHoaDon.getValueAt(i, 2) + ""));
                hdct.setSuDung(Integer.parseInt(tblChiTietHoaDon.getValueAt(i, 3) + ""));
                hdct.setGia(Double.parseDouble(tblChiTietHoaDon.getValueAt(i, 4) + ""));
                hdctDao.update(hdct);
            }
            HoaDon h = hdDao.selectByID(idHoaDon);
            h.setTrangThai(rdoDaThanhToan.isSelected());
            hdDao.update(h);
            JOptionPane.showMessageDialog(this, "Đã cập nhật");
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Nhập lại chỉ số điện nước");
        }

    }

    public void delete() {
        if (JOptionPane.showConfirmDialog(this, "Bạn chắc chăn muốn xóa") == 0) {
            hdctDao.delete(idHoaDon);
            hdDao.delete(idHoaDon);
            fillToHoaDon();
            JOptionPane.showMessageDialog(this, "Đã xóa");
            pnlContent.setSelectedIndex(0);
            moi();
        }
    }

    public void setStatus(boolean insert) {
        btnCapNhat.setEnabled(!insert);
        btnThem.setEnabled(insert);
        btnXoa.setEnabled(!insert);
        btnIn.setEnabled(!insert);
        pnlChonPhong.setVisible(insert);
        lblPhong.setVisible(!insert);
        rdoChuaThanhToan.setEnabled(!insert);
        rdoDaThanhToan.setEnabled(!insert);
    }

    public void printPDF() {
        String path = "";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);
        if (x == JFileChooser.APPROVE_OPTION) {
            path = j.getSelectedFile().getPath();
        }
        Document doc = new Document();
        try {
            String fileName = tblDanhSachHoaDon.getValueAt(indexHoaDon, 2) + "_" + tblDanhSachHoaDon.getValueAt(indexHoaDon, 1) + "_" + tblDanhSachHoaDon.getValueAt(indexHoaDon, 3);
            PdfWriter.getInstance(doc, new FileOutputStream(path + fileName + ".pdf"));
            doc.open();

            doc.addHeader(lblThangNam.getText(), "");

            PdfPTable tbl = new PdfPTable(6);
            tbl.addCell("Khoan thu");
            tbl.addCell("So cu");
            tbl.addCell("So moi");
            tbl.addCell("Su dung");
            tbl.addCell("Đon gia");
            tbl.addCell("Thành tien");

            for (int i = 0; i < tblChiTietHoaDon.getRowCount(); i++) {
                String khoanThu = tblChiTietHoaDon.getValueAt(i, 0).toString();
                String soCu = tblChiTietHoaDon.getValueAt(i, 1).toString();
                String soMoi = tblChiTietHoaDon.getValueAt(i, 2).toString();
                String suDung = tblChiTietHoaDon.getValueAt(i, 3).toString();
                String donGia = tblChiTietHoaDon.getValueAt(i, 4).toString();
                String thanhTien = tblChiTietHoaDon.getValueAt(i, 5).toString();

                tbl.addCell(khoanThu);
                tbl.addCell(soCu);
                tbl.addCell(soMoi);
                tbl.addCell(suDung);
                tbl.addCell(donGia);
                tbl.addCell(thanhTien);
            }

            Date date = java.util.Calendar.getInstance().getTime();
            Paragraph time = new Paragraph("                                                                                Ngay in: "+date + "", new Font(Font.FontFamily.TIMES_ROMAN, 13));
            double tongTien = 0;
            for (int i = 0; i <= tblChiTietHoaDon.getRowCount() - 1; i++) {
                tongTien = tongTien + Double.parseDouble(tblChiTietHoaDon.getValueAt(i, 5) + "");
            }
            Paragraph header = new Paragraph("                                                    HOA DON", new Font(Font.FontFamily.TIMES_ROMAN, 18));
            Paragraph trangThai = new Paragraph("               Trang thai hoa don: " + (rdoDaThanhToan.isSelected() == true ? "Da thanh toan" : "Chua thanh toan"), new Font(Font.FontFamily.TIMES_ROMAN, 13));
            Paragraph tongtien = new Paragraph("               Tong tien: " + tongTien + " VND", new Font(Font.FontFamily.TIMES_ROMAN, 13));
            Paragraph phong = new Paragraph("               Phong: " + lblPhong.getText(), new Font(Font.FontFamily.TIMES_ROMAN, 13));
            Paragraph thang = new Paragraph("               Thang thanh toan: " + tblDanhSachHoaDon.getValueAt(indexHoaDon, 3), new Font(Font.FontFamily.TIMES_ROMAN, 13));
            Paragraph enter = new Paragraph(" ");
            doc.add(header);
            doc.add(phong);
            doc.add(thang);
            doc.add(enter);
            doc.add(tbl);
            doc.add(tongtien);
            doc.add(trangThai);
            doc.add(time);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(HoaDonWindows.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(HoaDonWindows.class.getName()).log(Level.SEVERE, null, ex);
        }
        doc.close();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnIn;
    private javax.swing.JButton btnLuuChiSo;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboNam;
    private javax.swing.JComboBox<String> cboPhong;
    private javax.swing.JComboBox<String> cboThang;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblConPhong;
    private javax.swing.JLabel lblNam;
    private javax.swing.JLabel lblPhong;
    private javax.swing.JLabel lblSoToaNha2;
    private javax.swing.JLabel lblThang;
    private javax.swing.JLabel lblThangNam;
    private javax.swing.JLabel lblTienPhong;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JPanel pnlChiTietHoaDon;
    private javax.swing.JPanel pnlChonPhong;
    private javax.swing.JTabbedPane pnlContent;
    private javax.swing.JPanel pnlDanhSachHoaDon;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnl_Loc;
    private javax.swing.JRadioButton rdoChuaThanhToan;
    private javax.swing.JRadioButton rdoDaThanhToan;
    private javax.swing.JTable tblChiTietHoaDon;
    private javax.swing.JTable tblDanhSachHoaDon;
    private javax.swing.JTextField txtSoDienCu;
    private javax.swing.JTextField txtSoDienMoi;
    private javax.swing.JTextField txtSoDienSuDung;
    private javax.swing.JTextField txtSoNuocCu;
    private javax.swing.JTextField txtSoNuocMoi;
    private javax.swing.JTextField txtSoNuocSuDung;
    // End of variables declaration//GEN-END:variables

}
