/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.KhachThueDao;
import dao.TaiKhoanDao;
import helper.Auth;
import helper.DateHelper;
import helper.XJDBC;
import java.awt.Color;
//import helper.DateHelper;
//import helper.DialogHelper;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.KhachThue;
import model.TaiKhoan;

/**
 *
 * @author Admin
 */
public final class KhachThueWindows extends javax.swing.JPanel {

    /**
     * Creates new form Nha
     */
    int index;
    KhachThueDao dao = new KhachThueDao();
    DefaultTableModel model;
    int id;
    Color colorDisable = new Color(143, 167, 191);
    Color colorEnable = new Color(40, 63, 85);

    public KhachThueWindows() {
        initComponents();
        fillToGrid();
        setStatusButton(true);
        clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        pnlContent = new javax.swing.JTabbedPane();
        pnlDanhSachKhachThue = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKhachThue = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        pnlChiTietKhachThue = new javax.swing.JPanel();
        pnlHoVaTen = new javax.swing.JPanel();
        lblHoVaTen = new javax.swing.JLabel();
        txtHoVaTen = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        pnlNgaySinh = new javax.swing.JPanel();
        lblNgaySinh = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        pnlQueQuan = new javax.swing.JPanel();
        lblQueQuan = new javax.swing.JLabel();
        txtQueQuan = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        pnlDienThoai = new javax.swing.JPanel();
        lblDienThoai = new javax.swing.JLabel();
        txtDienThoai = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        pnlGhiChu = new javax.swing.JPanel();
        lblGhiChu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        pnlEmail = new javax.swing.JPanel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        pnlCMTND = new javax.swing.JPanel();
        lblCMTND = new javax.swing.JLabel();
        txtCMTND = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        pnlGioiTinh = new javax.swing.JPanel();
        lblGioiTinh = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        pnlBtnThem = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        pnlBtnCapNhat = new javax.swing.JPanel();
        btnCapNhat = new javax.swing.JButton();
        pnlBtnXoa = new javax.swing.JPanel();
        btnXoa = new javax.swing.JButton();
        pnlBtnMoi = new javax.swing.JPanel();
        btnMoi = new javax.swing.JButton();
        pnlTaoTaiKhoan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtMatKhau = new javax.swing.JPasswordField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblSoToaNha2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1030, 710));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlContent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pnlDanhSachKhachThue.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tblKhachThue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Họ tên", "Ngày sinh", "Giới tính", "Quê quán", "Điện thoại", "Email", "CMND", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhachThue.setGridColor(new java.awt.Color(204, 204, 204));
        tblKhachThue.setRowHeight(30);
        tblKhachThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachThueMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKhachThue);

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTimKiem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_24px.png"))); // NOI18N
        btnTimKiem.setBorder(null);
        btnTimKiem.setContentAreaFilled(false);
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDanhSachKhachThueLayout = new javax.swing.GroupLayout(pnlDanhSachKhachThue);
        pnlDanhSachKhachThue.setLayout(pnlDanhSachKhachThueLayout);
        pnlDanhSachKhachThueLayout.setHorizontalGroup(
            pnlDanhSachKhachThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhSachKhachThueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDanhSachKhachThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlDanhSachKhachThueLayout.setVerticalGroup(
            pnlDanhSachKhachThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhSachKhachThueLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlContent.addTab("Danh sách khách thuê", pnlDanhSachKhachThue);

        pnlChiTietKhachThue.setBackground(new java.awt.Color(255, 255, 255));
        pnlChiTietKhachThue.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHoVaTen.setBackground(new java.awt.Color(255, 255, 255));
        pnlHoVaTen.setForeground(new java.awt.Color(255, 255, 255));

        lblHoVaTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHoVaTen.setText("Họ và tên");

        txtHoVaTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtHoVaTen.setForeground(new java.awt.Color(102, 102, 102));
        txtHoVaTen.setBorder(null);

        javax.swing.GroupLayout pnlHoVaTenLayout = new javax.swing.GroupLayout(pnlHoVaTen);
        pnlHoVaTen.setLayout(pnlHoVaTenLayout);
        pnlHoVaTenLayout.setHorizontalGroup(
            pnlHoVaTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtHoVaTen)
            .addComponent(jSeparator3)
            .addGroup(pnlHoVaTenLayout.createSequentialGroup()
                .addComponent(lblHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        pnlHoVaTenLayout.setVerticalGroup(
            pnlHoVaTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHoVaTenLayout.createSequentialGroup()
                .addGroup(pnlHoVaTenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlHoVaTenLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlChiTietKhachThue.add(pnlHoVaTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 450, 70));

        pnlNgaySinh.setBackground(new java.awt.Color(255, 255, 255));
        pnlNgaySinh.setForeground(new java.awt.Color(255, 255, 255));

        lblNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNgaySinh.setText("Ngày sinh");

        txtNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNgaySinh.setForeground(new java.awt.Color(102, 102, 102));
        txtNgaySinh.setBorder(null);

        javax.swing.GroupLayout pnlNgaySinhLayout = new javax.swing.GroupLayout(pnlNgaySinh);
        pnlNgaySinh.setLayout(pnlNgaySinhLayout);
        pnlNgaySinhLayout.setHorizontalGroup(
            pnlNgaySinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtNgaySinh)
            .addComponent(jSeparator2)
            .addGroup(pnlNgaySinhLayout.createSequentialGroup()
                .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        pnlNgaySinhLayout.setVerticalGroup(
            pnlNgaySinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNgaySinhLayout.createSequentialGroup()
                .addGroup(pnlNgaySinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlNgaySinhLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlChiTietKhachThue.add(pnlNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 450, 70));

        pnlQueQuan.setBackground(new java.awt.Color(255, 255, 255));
        pnlQueQuan.setForeground(new java.awt.Color(255, 255, 255));

        lblQueQuan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblQueQuan.setText("Quê quán");

        txtQueQuan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtQueQuan.setForeground(new java.awt.Color(102, 102, 102));
        txtQueQuan.setBorder(null);

        javax.swing.GroupLayout pnlQueQuanLayout = new javax.swing.GroupLayout(pnlQueQuan);
        pnlQueQuan.setLayout(pnlQueQuanLayout);
        pnlQueQuanLayout.setHorizontalGroup(
            pnlQueQuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtQueQuan)
            .addComponent(jSeparator4)
            .addGroup(pnlQueQuanLayout.createSequentialGroup()
                .addComponent(lblQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        pnlQueQuanLayout.setVerticalGroup(
            pnlQueQuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQueQuanLayout.createSequentialGroup()
                .addGroup(pnlQueQuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlQueQuanLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pnlChiTietKhachThue.add(pnlQueQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, -1, -1));

        pnlDienThoai.setBackground(new java.awt.Color(255, 255, 255));
        pnlDienThoai.setForeground(new java.awt.Color(255, 255, 255));

        lblDienThoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDienThoai.setText("Điện thoại");

        txtDienThoai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtDienThoai.setForeground(new java.awt.Color(102, 102, 102));
        txtDienThoai.setBorder(null);

        javax.swing.GroupLayout pnlDienThoaiLayout = new javax.swing.GroupLayout(pnlDienThoai);
        pnlDienThoai.setLayout(pnlDienThoaiLayout);
        pnlDienThoaiLayout.setHorizontalGroup(
            pnlDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDienThoai)
            .addComponent(jSeparator5)
            .addGroup(pnlDienThoaiLayout.createSequentialGroup()
                .addComponent(lblDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        pnlDienThoaiLayout.setVerticalGroup(
            pnlDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDienThoaiLayout.createSequentialGroup()
                .addGroup(pnlDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDienThoaiLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pnlChiTietKhachThue.add(pnlDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, -1, -1));

        pnlGhiChu.setBackground(new java.awt.Color(255, 255, 255));

        lblGhiChu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGhiChu.setText("Ghi chú");

        txtGhiChu.setColumns(20);
        txtGhiChu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtGhiChu.setForeground(new java.awt.Color(102, 102, 102));
        txtGhiChu.setRows(5);
        txtGhiChu.setAutoscrolls(false);
        txtGhiChu.setBorder(null);
        jScrollPane1.setViewportView(txtGhiChu);

        javax.swing.GroupLayout pnlGhiChuLayout = new javax.swing.GroupLayout(pnlGhiChu);
        pnlGhiChu.setLayout(pnlGhiChuLayout);
        pnlGhiChuLayout.setHorizontalGroup(
            pnlGhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGhiChuLayout.createSequentialGroup()
                .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        pnlGhiChuLayout.setVerticalGroup(
            pnlGhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGhiChuLayout.createSequentialGroup()
                .addComponent(lblGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlChiTietKhachThue.add(pnlGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, 210));

        pnlEmail.setBackground(new java.awt.Color(255, 255, 255));
        pnlEmail.setForeground(new java.awt.Color(255, 255, 255));

        lblEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEmail.setText("Email");

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(102, 102, 102));
        txtEmail.setBorder(null);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEmailLayout = new javax.swing.GroupLayout(pnlEmail);
        pnlEmail.setLayout(pnlEmailLayout);
        pnlEmailLayout.setHorizontalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtEmail)
            .addComponent(jSeparator7)
            .addGroup(pnlEmailLayout.createSequentialGroup()
                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        pnlEmailLayout.setVerticalGroup(
            pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEmailLayout.createSequentialGroup()
                .addGroup(pnlEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlEmailLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pnlChiTietKhachThue.add(pnlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, -1, -1));

        pnlCMTND.setBackground(new java.awt.Color(255, 255, 255));
        pnlCMTND.setForeground(new java.awt.Color(255, 255, 255));

        lblCMTND.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCMTND.setText("CMTND");

        txtCMTND.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCMTND.setForeground(new java.awt.Color(102, 102, 102));
        txtCMTND.setBorder(null);

        javax.swing.GroupLayout pnlCMTNDLayout = new javax.swing.GroupLayout(pnlCMTND);
        pnlCMTND.setLayout(pnlCMTNDLayout);
        pnlCMTNDLayout.setHorizontalGroup(
            pnlCMTNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCMTND)
            .addComponent(jSeparator8)
            .addGroup(pnlCMTNDLayout.createSequentialGroup()
                .addComponent(lblCMTND, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        pnlCMTNDLayout.setVerticalGroup(
            pnlCMTNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCMTNDLayout.createSequentialGroup()
                .addGroup(pnlCMTNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCMTND, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCMTNDLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtCMTND, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pnlChiTietKhachThue.add(pnlCMTND, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, -1));

        pnlGioiTinh.setBackground(new java.awt.Color(255, 255, 255));
        pnlGioiTinh.setForeground(new java.awt.Color(255, 255, 255));

        lblGioiTinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGioiTinh.setText("Giói tính");

        rdoNam.setBackground(new java.awt.Color(255, 255, 255));
        Gender.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoNam.setSelected(true);
        rdoNam.setText("nam");

        rdoNu.setBackground(new java.awt.Color(255, 255, 255));
        Gender.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoNu.setText("Nữ");

        javax.swing.GroupLayout pnlGioiTinhLayout = new javax.swing.GroupLayout(pnlGioiTinh);
        pnlGioiTinh.setLayout(pnlGioiTinhLayout);
        pnlGioiTinhLayout.setHorizontalGroup(
            pnlGioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator9)
            .addGroup(pnlGioiTinhLayout.createSequentialGroup()
                .addGroup(pnlGioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlGioiTinhLayout.createSequentialGroup()
                        .addComponent(rdoNam)
                        .addGap(18, 18, 18)
                        .addComponent(rdoNu)))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        pnlGioiTinhLayout.setVerticalGroup(
            pnlGioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGioiTinhLayout.createSequentialGroup()
                .addComponent(lblGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(pnlGioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoNam)
                    .addComponent(rdoNu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlChiTietKhachThue.add(pnlGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        pnlBtnThem.setBackground(new java.awt.Color(40, 63, 85));

        btnThem.setBackground(new java.awt.Color(40, 63, 85));
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.setBorder(null);
        btnThem.setBorderPainted(false);
        btnThem.setContentAreaFilled(false);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnThemLayout = new javax.swing.GroupLayout(pnlBtnThem);
        pnlBtnThem.setLayout(pnlBtnThemLayout);
        pnlBtnThemLayout.setHorizontalGroup(
            pnlBtnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBtnThemLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlBtnThemLayout.setVerticalGroup(
            pnlBtnThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBtnThemLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlChiTietKhachThue.add(pnlBtnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        pnlBtnCapNhat.setBackground(new java.awt.Color(40, 63, 85));

        btnCapNhat.setBackground(new java.awt.Color(40, 63, 85));
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.setBorder(null);
        btnCapNhat.setBorderPainted(false);
        btnCapNhat.setContentAreaFilled(false);
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnCapNhatLayout = new javax.swing.GroupLayout(pnlBtnCapNhat);
        pnlBtnCapNhat.setLayout(pnlBtnCapNhatLayout);
        pnlBtnCapNhatLayout.setHorizontalGroup(
            pnlBtnCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        pnlBtnCapNhatLayout.setVerticalGroup(
            pnlBtnCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlChiTietKhachThue.add(pnlBtnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, -1, -1));

        pnlBtnXoa.setBackground(new java.awt.Color(40, 63, 85));

        btnXoa.setBackground(new java.awt.Color(40, 63, 85));
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.setBorderPainted(false);
        btnXoa.setContentAreaFilled(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnXoaLayout = new javax.swing.GroupLayout(pnlBtnXoa);
        pnlBtnXoa.setLayout(pnlBtnXoaLayout);
        pnlBtnXoaLayout.setHorizontalGroup(
            pnlBtnXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        pnlBtnXoaLayout.setVerticalGroup(
            pnlBtnXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlChiTietKhachThue.add(pnlBtnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, -1, -1));

        pnlBtnMoi.setBackground(new java.awt.Color(40, 63, 85));

        btnMoi.setBackground(new java.awt.Color(40, 63, 85));
        btnMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnMoi.setText("Mới");
        btnMoi.setBorderPainted(false);
        btnMoi.setContentAreaFilled(false);
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnMoiLayout = new javax.swing.GroupLayout(pnlBtnMoi);
        pnlBtnMoi.setLayout(pnlBtnMoiLayout);
        pnlBtnMoiLayout.setHorizontalGroup(
            pnlBtnMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        pnlBtnMoiLayout.setVerticalGroup(
            pnlBtnMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlChiTietKhachThue.add(pnlBtnMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, -1, -1));

        pnlTaoTaiKhoan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tạo tài khoản:");

        txtTaiKhoan.setBorder(null);

        txtMatKhau.setBorder(null);

        jLabel1.setText("Tài khoản");

        jLabel3.setText("Mật khẩu");

        javax.swing.GroupLayout pnlTaoTaiKhoanLayout = new javax.swing.GroupLayout(pnlTaoTaiKhoan);
        pnlTaoTaiKhoan.setLayout(pnlTaoTaiKhoanLayout);
        pnlTaoTaiKhoanLayout.setHorizontalGroup(
            pnlTaoTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaoTaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTaoTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlTaoTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTaoTaiKhoanLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(pnlTaoTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        pnlTaoTaiKhoanLayout.setVerticalGroup(
            pnlTaoTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTaoTaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(pnlTaoTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlTaoTaiKhoanLayout.createSequentialGroup()
                    .addGap(0, 105, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(68, 68, 68)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 5, Short.MAX_VALUE)))
        );

        pnlChiTietKhachThue.add(pnlTaoTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 470, 190));

        pnlContent.addTab("Chi tiết khách thuê", pnlChiTietKhachThue);

        jPanel3.setBackground(new java.awt.Color(40, 63, 85));

        lblSoToaNha2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSoToaNha2.setForeground(new java.awt.Color(255, 255, 255));
        lblSoToaNha2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoToaNha2.setText("Khách thuê");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSoToaNha2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSoToaNha2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1010, 710));
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        fillToGrid();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblKhachThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachThueMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            index = tblKhachThue.getRowCount();
            this.index = tblKhachThue.rowAtPoint(evt.getPoint());
            if (this.index >= 0) {
                this.edit();
                pnlContent.setSelectedIndex(1);
            }
        }
    }//GEN-LAST:event_tblKhachThueMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Gender;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblCMTND;
    private javax.swing.JLabel lblDienThoai;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblHoVaTen;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblQueQuan;
    private javax.swing.JLabel lblSoToaNha2;
    private javax.swing.JPanel pnlBtnCapNhat;
    private javax.swing.JPanel pnlBtnMoi;
    private javax.swing.JPanel pnlBtnThem;
    private javax.swing.JPanel pnlBtnXoa;
    private javax.swing.JPanel pnlCMTND;
    private javax.swing.JPanel pnlChiTietKhachThue;
    private javax.swing.JTabbedPane pnlContent;
    private javax.swing.JPanel pnlDanhSachKhachThue;
    private javax.swing.JPanel pnlDienThoai;
    private javax.swing.JPanel pnlEmail;
    private javax.swing.JPanel pnlGhiChu;
    private javax.swing.JPanel pnlGioiTinh;
    private javax.swing.JPanel pnlHoVaTen;
    private javax.swing.JPanel pnlNgaySinh;
    private javax.swing.JPanel pnlQueQuan;
    private javax.swing.JPanel pnlTaoTaiKhoan;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblKhachThue;
    private javax.swing.JTextField txtCMTND;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtHoVaTen;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextField txtTaiKhoan;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    public void fillToGrid() {
        model = (DefaultTableModel) tblKhachThue.getModel();
        model.setRowCount(0);
        String name = txtTimKiem.getText();
        List<KhachThue> list = dao.selectByName(name);
        for (KhachThue kh : list) {
            Object[] row = new Object[]{kh.getIdKhachThue(), kh.getHoTen(), kh.getNgaySinh(), kh.isGioiTinh() == true ? "Nam" : "Nữ",
                kh.getQueQuan(), kh.getDienThoai(), kh.getEmail(), kh.getcMND(), kh.getGhiChu()};
            model.addRow(row);
        }
    }
    TaiKhoanDao tkDao = new TaiKhoanDao();

    private void insert() {
        KhachThue objKhachThue = getModel();
        try {
            if (check()) {
                return;
            }
            if(txtTaiKhoan.getText().equals("") || txtMatKhau.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Nhập tài khoản, mật khẩu");
                return;
            }
            dao.insert(objKhachThue);
            this.fillToGrid();
            tkDao.insert(new TaiKhoan(txtTaiKhoan.getText(), txtMatKhau.getText(), "", Integer.parseInt(tblKhachThue.getValueAt(tblKhachThue.getRowCount() - 1, 0) + ""), false));
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Thêm thất bại!");
        }
    }

    private void delete() {
        if (JOptionPane.showConfirmDialog(this, "Bạn thực sự muốn xóa?") == 0) {
            try {
                dao.delete(id);
                this.fillToGrid();
                this.clear();
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
            } catch (HeadlessException e) {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        }
    }

    private void update() {
        KhachThue objKhachThue = getModel();
        try {
            if (check()) {
                return;
            }
            dao.update(objKhachThue);
            this.fillToGrid();
            JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
        }

    }

    private KhachThue getModel() {
        KhachThue objKhachThue = new KhachThue();
        try {
            objKhachThue.setHoTen(txtHoVaTen.getText());
            objKhachThue.setNgaySinh(DateHelper.toDate(txtNgaySinh.getText(), "dd/MM/yyyy"));
            objKhachThue.setGioiTinh(rdoNam.isSelected());
            objKhachThue.setQueQuan(txtQueQuan.getText());
            objKhachThue.setDienThoai(txtDienThoai.getText());
            objKhachThue.setEmail(txtEmail.getText());
            objKhachThue.setcMND(txtCMTND.getText());
            objKhachThue.setGhiChu(txtGhiChu.getText());
            objKhachThue.setIdKhachThue(id);
            return objKhachThue;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ngày sinh phải đúng định dạng - yyyy/MM/dd");
            return null;
        }
    }

    private void clear() {
        KhachThue objKhachThue = new KhachThue();
        this.setModel(objKhachThue);
        setStatusButton(true);
    }

    private void setModel(KhachThue objKhachThue) {
        txtHoVaTen.setText(objKhachThue.getHoTen());
        txtNgaySinh.setText(String.valueOf(objKhachThue.getNgaySinh()));
        rdoNam.setSelected(objKhachThue.isGioiTinh());
        rdoNu.setSelected(!objKhachThue.isGioiTinh());
        txtQueQuan.setText(objKhachThue.getQueQuan());
        txtDienThoai.setText(objKhachThue.getDienThoai());
        txtEmail.setText(objKhachThue.getEmail());
        txtCMTND.setText(objKhachThue.getcMND());
        txtGhiChu.setText(objKhachThue.getGhiChu());
    }

    private void edit() {
        try {
            id = Integer.parseInt(tblKhachThue.getValueAt(this.index, 0) + "");
            KhachThue kt = dao.selectByID(id);
            if (kt != null) {
                this.setModel(kt);
                setStatusButton(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
//            JOptionPane.showMessageDialog(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    private boolean check() {
        String pattern = "\\w+@\\w+\\.\\w+";
        if (txtHoVaTen.getText().equals("") || txtNgaySinh.getText().equals("") || txtQueQuan.getText().equals("") || txtDienThoai.getText().equals("") || txtCMTND.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Yêu cầu nhập đầy đủ thông tin!");
            return true;
        }
        if (txtEmail.getText().length() > 0 && !txtEmail.getText().matches(pattern)) {
            JOptionPane.showMessageDialog(this, "Yêu cầu nhập đúng định dạng của email!");
            txtEmail.requestFocus();
            return true;
        }

        return false;
    }

    public void setStatusButton(Boolean status) {
        btnThem.setEnabled(status);
        btnCapNhat.setEnabled(!status);
        btnXoa.setEnabled(!status);
        pnlTaoTaiKhoan.setVisible(status);
        if (status == true) {
            pnlBtnThem.setBackground(colorEnable);
            pnlBtnCapNhat.setBackground(colorDisable);
            pnlBtnXoa.setBackground(colorDisable);
        } else {
            pnlBtnThem.setBackground(colorDisable);
            pnlBtnCapNhat.setBackground(colorEnable);
            pnlBtnXoa.setBackground(colorEnable);
        }
    }


}
