/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.InFoDao;
import helper.Auth;
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public final class MainWindows extends javax.swing.JFrame {
    Color c = new Color(143, 167, 191);
    Color c1 = new Color(40, 63, 85);
    InFoDao inFoDao;
    TrangChuWindows trangChu;
    ToaNhaWindows nha;
    PhongWindows phong;
    KhachThueWindows khachThue;
    DichVuWindows dichvu;
    HoaDonWindows hoadon;
    SuCoWindows suco;
    MoTaWindows mota;

    /**
     * Creates new form Main
     */
    public MainWindows() {
        initComponents();
        new DangNhapJDialog(this, true).setVisible(true);
        setLocationRelativeTo(this);
        if (Auth.user.isRoles() == false) {
            pnlNguoiThue.setVisible(false);
            pnlThuChi.setVisible(false);
            pnlThuChi.setVisible(false);
            pnlTrangChu.setVisible(false);
            lblUsername.setText(Auth.user.getHovaten());
            openPhong();
        }
        else{
            lblUsername.setText("Admin");
            openTrangChu();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenu = new javax.swing.JPanel();
        lblIconUser = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        pnlTrangChu = new javax.swing.JPanel();
        lblTrangChu = new javax.swing.JLabel();
        pnlToaNha = new javax.swing.JPanel();
        lblToaNha = new javax.swing.JLabel();
        pnlPhong = new javax.swing.JPanel();
        lblPhong = new javax.swing.JLabel();
        pnlNguoiThue = new javax.swing.JPanel();
        lblNguoiThue = new javax.swing.JLabel();
        pnlDichVu = new javax.swing.JPanel();
        lblDichVu = new javax.swing.JLabel();
        pnlHoaDon = new javax.swing.JPanel();
        lblHoaDon = new javax.swing.JLabel();
        pnlSuCo = new javax.swing.JPanel();
        lblSuCO = new javax.swing.JLabel();
        pnlThuChi = new javax.swing.JPanel();
        lblThuChi = new javax.swing.JLabel();
        pnlDoiMatKhau = new javax.swing.JPanel();
        lblDoiMatKhau = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QUẢN LÝ NHÀ TRỌ");
        setResizable(false);

        pnlMenu.setBackground(new java.awt.Color(40, 63, 85));

        lblIconUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/male_user2_72px.png"))); // NOI18N
        lblIconUser.setToolTipText("");
        lblIconUser.setMaximumSize(new java.awt.Dimension(250, 72));
        lblIconUser.setMinimumSize(new java.awt.Dimension(250, 72));
        lblIconUser.setPreferredSize(new java.awt.Dimension(250, 72));
        pnlMenu.add(lblIconUser);

        lblUsername.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("Nguyễn Ngọc Tuấn");
        pnlMenu.add(lblUsername);

        pnlTrangChu.setBackground(new java.awt.Color(40, 63, 85));
        pnlTrangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlTrangChuMouseClicked(evt);
            }
        });

        lblTrangChu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        lblTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home_24px.png"))); // NOI18N
        lblTrangChu.setText("Trang chủ");

        javax.swing.GroupLayout pnlTrangChuLayout = new javax.swing.GroupLayout(pnlTrangChu);
        pnlTrangChu.setLayout(pnlTrangChuLayout);
        pnlTrangChuLayout.setHorizontalGroup(
            pnlTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTrangChuLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lblTrangChu)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        pnlTrangChuLayout.setVerticalGroup(
            pnlTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlTrangChu);

        pnlToaNha.setBackground(new java.awt.Color(40, 63, 85));
        pnlToaNha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlToaNhaMouseClicked(evt);
            }
        });

        lblToaNha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblToaNha.setForeground(new java.awt.Color(255, 255, 255));
        lblToaNha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/real_estate_24px.png"))); // NOI18N
        lblToaNha.setText("Tòa nhà");

        javax.swing.GroupLayout pnlToaNhaLayout = new javax.swing.GroupLayout(pnlToaNha);
        pnlToaNha.setLayout(pnlToaNhaLayout);
        pnlToaNhaLayout.setHorizontalGroup(
            pnlToaNhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToaNhaLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lblToaNha)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        pnlToaNhaLayout.setVerticalGroup(
            pnlToaNhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblToaNha, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlToaNha);

        pnlPhong.setBackground(new java.awt.Color(40, 63, 85));
        pnlPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPhongMouseClicked(evt);
            }
        });

        lblPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPhong.setForeground(new java.awt.Color(255, 255, 255));
        lblPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/room_24px.png"))); // NOI18N
        lblPhong.setText("Phòng");

        javax.swing.GroupLayout pnlPhongLayout = new javax.swing.GroupLayout(pnlPhong);
        pnlPhong.setLayout(pnlPhongLayout);
        pnlPhongLayout.setHorizontalGroup(
            pnlPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPhongLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lblPhong)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        pnlPhongLayout.setVerticalGroup(
            pnlPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlPhong);

        pnlNguoiThue.setBackground(new java.awt.Color(40, 63, 85));
        pnlNguoiThue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlNguoiThueMouseClicked(evt);
            }
        });

        lblNguoiThue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNguoiThue.setForeground(new java.awt.Color(255, 255, 255));
        lblNguoiThue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/people_24px.png"))); // NOI18N
        lblNguoiThue.setText("Khách thuê");

        javax.swing.GroupLayout pnlNguoiThueLayout = new javax.swing.GroupLayout(pnlNguoiThue);
        pnlNguoiThue.setLayout(pnlNguoiThueLayout);
        pnlNguoiThueLayout.setHorizontalGroup(
            pnlNguoiThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNguoiThueLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lblNguoiThue)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        pnlNguoiThueLayout.setVerticalGroup(
            pnlNguoiThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNguoiThue, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlNguoiThue);

        pnlDichVu.setBackground(new java.awt.Color(40, 63, 85));
        pnlDichVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDichVuMouseClicked(evt);
            }
        });

        lblDichVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDichVu.setForeground(new java.awt.Color(255, 255, 255));
        lblDichVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/light_24px.png"))); // NOI18N
        lblDichVu.setText("Dịch vụ");

        javax.swing.GroupLayout pnlDichVuLayout = new javax.swing.GroupLayout(pnlDichVu);
        pnlDichVu.setLayout(pnlDichVuLayout);
        pnlDichVuLayout.setHorizontalGroup(
            pnlDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDichVuLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lblDichVu)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        pnlDichVuLayout.setVerticalGroup(
            pnlDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDichVu, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlDichVu);

        pnlHoaDon.setBackground(new java.awt.Color(40, 63, 85));
        pnlHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlHoaDonMouseClicked(evt);
            }
        });

        lblHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        lblHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bill_24px.png"))); // NOI18N
        lblHoaDon.setText("Hóa đơn");

        javax.swing.GroupLayout pnlHoaDonLayout = new javax.swing.GroupLayout(pnlHoaDon);
        pnlHoaDon.setLayout(pnlHoaDonLayout);
        pnlHoaDonLayout.setHorizontalGroup(
            pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHoaDonLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lblHoaDon)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        pnlHoaDonLayout.setVerticalGroup(
            pnlHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlHoaDon);

        pnlSuCo.setBackground(new java.awt.Color(40, 63, 85));
        pnlSuCo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlSuCoMouseClicked(evt);
            }
        });

        lblSuCO.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSuCO.setForeground(new java.awt.Color(255, 255, 255));
        lblSuCO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/warning_shield_24px.png"))); // NOI18N
        lblSuCO.setText("Sự cố");

        javax.swing.GroupLayout pnlSuCoLayout = new javax.swing.GroupLayout(pnlSuCo);
        pnlSuCo.setLayout(pnlSuCoLayout);
        pnlSuCoLayout.setHorizontalGroup(
            pnlSuCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuCoLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lblSuCO)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        pnlSuCoLayout.setVerticalGroup(
            pnlSuCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSuCO, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlSuCo);

        pnlThuChi.setBackground(new java.awt.Color(40, 63, 85));
        pnlThuChi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlThuChiMouseClicked(evt);
            }
        });

        lblThuChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblThuChi.setForeground(new java.awt.Color(255, 255, 255));
        lblThuChi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/graph_report_script_24px.png"))); // NOI18N
        lblThuChi.setText("Khoản thu");

        javax.swing.GroupLayout pnlThuChiLayout = new javax.swing.GroupLayout(pnlThuChi);
        pnlThuChi.setLayout(pnlThuChiLayout);
        pnlThuChiLayout.setHorizontalGroup(
            pnlThuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThuChiLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(lblThuChi)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        pnlThuChiLayout.setVerticalGroup(
            pnlThuChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblThuChi, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlThuChi);

        pnlDoiMatKhau.setBackground(new java.awt.Color(40, 63, 85));
        pnlDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlDoiMatKhauMouseClicked(evt);
            }
        });

        lblDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDoiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lblDoiMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/password_window_24px.png"))); // NOI18N
        lblDoiMatKhau.setText("Đổi mật khẩu");

        javax.swing.GroupLayout pnlDoiMatKhauLayout = new javax.swing.GroupLayout(pnlDoiMatKhau);
        pnlDoiMatKhau.setLayout(pnlDoiMatKhauLayout);
        pnlDoiMatKhauLayout.setHorizontalGroup(
            pnlDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDoiMatKhauLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lblDoiMatKhau)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        pnlDoiMatKhauLayout.setVerticalGroup(
            pnlDoiMatKhauLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDoiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pnlMenu.add(pnlDoiMatKhau);

        desktop.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlTrangChuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTrangChuMouseClicked
        // TODO add your handling code here:
        openTrangChu();
    }//GEN-LAST:event_pnlTrangChuMouseClicked

    private void pnlToaNhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlToaNhaMouseClicked
        // TODO add your handling code here:
        nha = new ToaNhaWindows();
        nha.setBounds(0, 0, 1030, 720);
        nha.setVisible(true);
        desktop.removeAll();
        desktop.add(nha);

        pnlTrangChu.setBackground(c1);
        pnlToaNha.setBackground(c);
        pnlPhong.setBackground(c1);
        pnlNguoiThue.setBackground(c1);
        pnlDichVu.setBackground(c1);
        pnlHoaDon.setBackground(c1);
        pnlSuCo.setBackground(c1);
        pnlThuChi.setBackground(c1);
        pnlDoiMatKhau.setBackground(c1);
    }//GEN-LAST:event_pnlToaNhaMouseClicked

    private void pnlPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPhongMouseClicked
        // TODO add your handling code here:
        openPhong();

        pnlTrangChu.setBackground(c1);
        pnlToaNha.setBackground(c1);
        pnlPhong.setBackground(c);
        pnlNguoiThue.setBackground(c1);
        pnlDichVu.setBackground(c1);
        pnlHoaDon.setBackground(c1);
        pnlSuCo.setBackground(c1);
        pnlThuChi.setBackground(c1);
        pnlDoiMatKhau.setBackground(c1);
    }//GEN-LAST:event_pnlPhongMouseClicked

    private void pnlNguoiThueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNguoiThueMouseClicked
        // TODO add your handling code here:
        khachThue = new KhachThueWindows();
        khachThue.setBounds(0, 0, 1030, 720);
        khachThue.setVisible(true);
        desktop.removeAll();
        desktop.add(khachThue);

        pnlTrangChu.setBackground(c1);
        pnlToaNha.setBackground(c1);
        pnlPhong.setBackground(c1);
        pnlNguoiThue.setBackground(c);
        pnlDichVu.setBackground(c1);
        pnlHoaDon.setBackground(c1);
        pnlSuCo.setBackground(c1);
        pnlThuChi.setBackground(c1);
        pnlDoiMatKhau.setBackground(c1);
    }//GEN-LAST:event_pnlNguoiThueMouseClicked

    private void pnlDichVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDichVuMouseClicked
        // TODO add your handling code here:
        dichvu = new DichVuWindows();
        dichvu.setBounds(0, 0, 1030, 720);
        dichvu.setVisible(true);
        desktop.removeAll();
        desktop.add(dichvu);

        pnlTrangChu.setBackground(c1);
        pnlToaNha.setBackground(c1);
        pnlPhong.setBackground(c1);
        pnlNguoiThue.setBackground(c1);
        pnlDichVu.setBackground(c);
        pnlHoaDon.setBackground(c1);
        pnlSuCo.setBackground(c1);
        pnlThuChi.setBackground(c1);
        pnlDoiMatKhau.setBackground(c1);
    }//GEN-LAST:event_pnlDichVuMouseClicked

    private void pnlHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHoaDonMouseClicked
        // TODO add your handling code here:
        hoadon = new HoaDonWindows();
        hoadon.setBounds(0, 0, 1030, 720);
        hoadon.setVisible(true);
        desktop.removeAll();
        desktop.add(hoadon);

        pnlTrangChu.setBackground(c1);
        pnlToaNha.setBackground(c1);
        pnlPhong.setBackground(c1);
        pnlNguoiThue.setBackground(c1);
        pnlDichVu.setBackground(c1);
        pnlHoaDon.setBackground(c);
        pnlSuCo.setBackground(c1);
        pnlThuChi.setBackground(c1);
        pnlDoiMatKhau.setBackground(c1);
    }//GEN-LAST:event_pnlHoaDonMouseClicked

    private void pnlSuCoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlSuCoMouseClicked
        // TODO add your handling code here:
        suco = new SuCoWindows();
        suco.setBounds(0, 0, 1030, 720);
        suco.setVisible(true);
        desktop.removeAll();
        desktop.add(suco);

        pnlTrangChu.setBackground(c1);
        pnlToaNha.setBackground(c1);
        pnlPhong.setBackground(c1);
        pnlNguoiThue.setBackground(c1);
        pnlDichVu.setBackground(c1);
        pnlHoaDon.setBackground(c1);
        pnlSuCo.setBackground(c);
        pnlThuChi.setBackground(c1);
        pnlDoiMatKhau.setBackground(c1);
    }//GEN-LAST:event_pnlSuCoMouseClicked

    private void pnlThuChiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlThuChiMouseClicked
        pnlTrangChu.setBackground(c1);
        pnlToaNha.setBackground(c1);
        pnlPhong.setBackground(c1);
        pnlNguoiThue.setBackground(c1);
        pnlDichVu.setBackground(c1);
        pnlHoaDon.setBackground(c1);
        pnlSuCo.setBackground(c1);
        pnlThuChi.setBackground(c);
        pnlDoiMatKhau.setBackground(c1);
        
        ThuChi ThuChi = new ThuChi();
        ThuChi.setBounds(0, 0, 1030, 720);
        ThuChi.setVisible(true);
        desktop.removeAll();
        desktop.add(ThuChi);
    }//GEN-LAST:event_pnlThuChiMouseClicked

    private void pnlDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlDoiMatKhauMouseClicked
        pnlTrangChu.setBackground(c1);
        pnlToaNha.setBackground(c1);
        pnlPhong.setBackground(c1);
        pnlNguoiThue.setBackground(c1);
        pnlDichVu.setBackground(c1);
        pnlHoaDon.setBackground(c1);
        pnlSuCo.setBackground(c1);
        pnlThuChi.setBackground(c1);
        pnlDoiMatKhau.setBackground(c);

        new DoiMatKhauJDialog(this, true).setVisible(true);
    }//GEN-LAST:event_pnlDoiMatKhauMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainWindows().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane desktop;
    private javax.swing.JLabel lblDichVu;
    private javax.swing.JLabel lblDoiMatKhau;
    private javax.swing.JLabel lblHoaDon;
    private javax.swing.JLabel lblIconUser;
    private javax.swing.JLabel lblNguoiThue;
    private javax.swing.JLabel lblPhong;
    private javax.swing.JLabel lblSuCO;
    private javax.swing.JLabel lblThuChi;
    private javax.swing.JLabel lblToaNha;
    private javax.swing.JLabel lblTrangChu;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlDichVu;
    private javax.swing.JPanel pnlDoiMatKhau;
    private javax.swing.JPanel pnlHoaDon;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlNguoiThue;
    private javax.swing.JPanel pnlPhong;
    private javax.swing.JPanel pnlSuCo;
    private javax.swing.JPanel pnlThuChi;
    private javax.swing.JPanel pnlToaNha;
    private javax.swing.JPanel pnlTrangChu;
    // End of variables declaration//GEN-END:variables

    public void openTrangChu() {
        trangChu = new TrangChuWindows();
        trangChu.setBounds(0, 0, 1030, 720);
        trangChu.setVisible(true);
        desktop.removeAll();
        desktop.add(trangChu);
        //add sự kiện click 2 lần vào bảng phòng trống - trang chủ
        TrangChuWindows.tblPhongTrong.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachPhongTrongMouseClicked(evt);
            }
        });
        pnlTrangChu.setBackground(c);
        pnlToaNha.setBackground(c1);
        pnlPhong.setBackground(c1);
        pnlNguoiThue.setBackground(c1);
        pnlDichVu.setBackground(c1);
        pnlHoaDon.setBackground(c1);
        pnlSuCo.setBackground(c1);
        pnlThuChi.setBackground(c1);
        pnlDoiMatKhau.setBackground(c1);
    }

    private void tblDanhSachPhongTrongMouseClicked(java.awt.event.MouseEvent evt) {
        if (evt.getClickCount() == 2) {
            int id = Integer.parseInt(TrangChuWindows.tblPhongTrong.getValueAt(TrangChuWindows.index1, 0) + "");
            mota = new MoTaWindows(this, true, id);
            if (Auth.user.isRoles() == false) {
                mota.btnLuuTienIch.setVisible(false);
            }
            mota.setVisible(true);

        }
    }

    private void openPhong() {
        phong = new PhongWindows();
        phong.setBounds(0, 0, 1030, 720);
        phong.setVisible(true);
        desktop.removeAll();
        desktop.add(phong);
    }

}
