/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.MoTaDao;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class MoTaWindows extends javax.swing.JDialog {
    public int id;
    /**
     * Creates new form PhongChiTiet
     */
    public MoTaWindows(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }

    public MoTaWindows(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        setStatus(id);
        this.id = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        chkLoc1 = new javax.swing.JCheckBox();
        chkLoc8 = new javax.swing.JCheckBox();
        chkLoc7 = new javax.swing.JCheckBox();
        chkLoc4 = new javax.swing.JCheckBox();
        chkLoc6 = new javax.swing.JCheckBox();
        chkLoc3 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnLuuTienIch = new javax.swing.JButton();
        chkLoc5 = new javax.swing.JCheckBox();
        chkLoc9 = new javax.swing.JCheckBox();
        chkLoc2 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        chkLoc1.setBackground(new java.awt.Color(255, 255, 255));
        chkLoc1.setText("Có sẵn điều hòa");
        chkLoc1.setToolTipText("DieuHoa");

        chkLoc8.setBackground(new java.awt.Color(255, 255, 255));
        chkLoc8.setText("Đồng hồ điện nước riêng");
        chkLoc8.setToolTipText("KhepKin");

        chkLoc7.setBackground(new java.awt.Color(255, 255, 255));
        chkLoc7.setText("Giờ ra vào tự do");
        chkLoc7.setToolTipText("ChoDeXe");

        chkLoc4.setBackground(new java.awt.Color(255, 255, 255));
        chkLoc4.setText("Ở chung chủ");
        chkLoc4.setToolTipText("ChungChu");

        chkLoc6.setBackground(new java.awt.Color(255, 255, 255));
        chkLoc6.setText("Nhà vệ sinh khép kín");
        chkLoc6.setToolTipText("ChoPhoiDoRieng");

        chkLoc3.setBackground(new java.awt.Color(255, 255, 255));
        chkLoc3.setText("Có chỗ để xe");
        chkLoc3.setToolTipText("Camera");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        btnLuuTienIch.setForeground(new java.awt.Color(255, 255, 255));
        btnLuuTienIch.setText("Lưu");
        btnLuuTienIch.setBorderPainted(false);
        btnLuuTienIch.setContentAreaFilled(false);
        btnLuuTienIch.setFocusPainted(false);
        btnLuuTienIch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuTienIchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLuuTienIch, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnLuuTienIch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.add(jPanel2);

        chkLoc5.setBackground(new java.awt.Color(255, 255, 255));
        chkLoc5.setText("Được nấu ăn trong phòng");
        chkLoc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLoc5ActionPerformed(evt);
            }
        });

        chkLoc9.setBackground(new java.awt.Color(255, 255, 255));
        chkLoc9.setText("Có khu phơi đồ riêng");

        chkLoc2.setBackground(new java.awt.Color(255, 255, 255));
        chkLoc2.setText("Có sẵn bình nước nóng lạnh");
        chkLoc2.setToolTipText("DieuHoa");
        chkLoc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLoc2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MÔ TẢ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(chkLoc3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chkLoc4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chkLoc5)
                            .addComponent(chkLoc1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(chkLoc2)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(chkLoc7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkLoc6))
                    .addComponent(chkLoc8)
                    .addComponent(chkLoc9))
                .addGap(47, 47, 47))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkLoc1)
                    .addComponent(chkLoc6))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkLoc2)
                            .addComponent(chkLoc7))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkLoc3)
                            .addComponent(chkLoc8)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkLoc4)
                            .addComponent(chkLoc9))))
                .addGap(31, 31, 31)
                .addComponent(chkLoc5)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuTienIchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuTienIchActionPerformed
        // TODO add your handling code here:
        save();
    }//GEN-LAST:event_btnLuuTienIchActionPerformed

    private void chkLoc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLoc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkLoc2ActionPerformed

    private void chkLoc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLoc5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkLoc5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoTaWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoTaWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoTaWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoTaWindows.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MoTaWindows dialog = new MoTaWindows(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    MoTaDao dao = new MoTaDao();

    public void setStatus(int id) {
        model.MoTa t = dao.setStatus(id);
        chkLoc1.setSelected(t.isLoc1());
        chkLoc2.setSelected(t.isLoc2());
        chkLoc3.setSelected(t.isLoc3());
        chkLoc4.setSelected(t.isLoc4());
        chkLoc5.setSelected(t.isLoc5());
        chkLoc6.setSelected(t.isLoc6());
        chkLoc7.setSelected(t.isLoc7());
        chkLoc8.setSelected(t.isLoc8());
        chkLoc9.setSelected(t.isLoc9());
    }

    public void save() {
        model.MoTa t = new model.MoTa(id, chkLoc1.isSelected(), chkLoc2.isSelected(), chkLoc3.isSelected(), chkLoc4.isSelected(),
                chkLoc5.isSelected(), chkLoc6.isSelected(), chkLoc7.isSelected(), chkLoc8.isSelected(), chkLoc9.isSelected());
        dao.updatemota(t);
        JOptionPane.showMessageDialog(this, "Đã lưu");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnLuuTienIch;
    private javax.swing.JCheckBox chkLoc1;
    private javax.swing.JCheckBox chkLoc2;
    private javax.swing.JCheckBox chkLoc3;
    private javax.swing.JCheckBox chkLoc4;
    private javax.swing.JCheckBox chkLoc5;
    private javax.swing.JCheckBox chkLoc6;
    private javax.swing.JCheckBox chkLoc7;
    private javax.swing.JCheckBox chkLoc8;
    private javax.swing.JCheckBox chkLoc9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
