/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.DichVuDao;
import dao.DichVuPhongDao;
import dao.HoaDonChiTietDao;
import dao.HoaDonDao;
import dao.KhachThueDao;
import dao.PhongDao;
import dao.MoTaDao;
import dao.ToaNhaDao;
import helper.Auth;
import helper.XJDBC;
import java.awt.Color;
import java.awt.HeadlessException;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.DichVu;
import model.DichVuPhong;
import model.HoaDon;
import model.HoaDonChiTiet;
import model.KhachThue;
import model.MoTa;
import model.Phong;
import model.ToaNha;

/**
 *
 * @author Admin
 */
public final class PhongWindows extends javax.swing.JPanel {

    Color colorDisable = new Color(143, 167, 191);
    Color colorEnable = new Color(40, 63, 85);

    /**
     * Creates new form Nha
     */
    public PhongWindows() {
        initComponents();
        filltoCbo();
        filltocboNha();
        filltotablephongbytimkiem();
        setStatus(true);
        if (Auth.user.isRoles() == false) {
            btnApDung.setVisible(false);
            btnCapNhatDichVu.setEnabled(false);
            btnThemDichVuPhong.setEnabled(false);
            btnThem_NguoiThuePhong.setEnabled(false);
            btnXoa_NguoiThuePhong.setEnabled(false);
            pnlBtnXoa_NguoiThuePhong.setVisible(false);
            pnlBtnXoa_DichVuPhong.setVisible(false);
            pnlBtnThem_NguoiThuePhong.setVisible(false);
            pnlBtnXoa_NguoiThuePhong.setVisible(false);
            pnl_ThemDichVu.setVisible(false);
            btnCapNhatDichVu.setVisible(false);
            pnlButton.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        pnlContent = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPhong = new javax.swing.JTable();
        txtTimKiem2 = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cboLoc = new javax.swing.JComboBox<>();
        chkDaThue = new javax.swing.JCheckBox();
        chkChuaThue = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnApDung = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlChiTietPhong = new javax.swing.JPanel();
        pnlNoiDungChiTietPhong = new javax.swing.JTabbedPane();
        pnlThongTinPhong = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        txtPhong = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDienTich = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtMoTa = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTang = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        cboNha = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        txtGia = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        txtTrangThai = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        pnlMoTaKhac = new javax.swing.JPanel();
        chkLoc1 = new javax.swing.JCheckBox();
        chkLoc6 = new javax.swing.JCheckBox();
        chkLoc7 = new javax.swing.JCheckBox();
        chkLoc2 = new javax.swing.JCheckBox();
        chkLoc3 = new javax.swing.JCheckBox();
        chkLoc8 = new javax.swing.JCheckBox();
        chkLoc9 = new javax.swing.JCheckBox();
        chkLoc4 = new javax.swing.JCheckBox();
        chkLoc5 = new javax.swing.JCheckBox();
        pnlButton = new javax.swing.JPanel();
        pnlThem = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        pnlCapNhat = new javax.swing.JPanel();
        btnCapNhat = new javax.swing.JButton();
        pnlXoa = new javax.swing.JPanel();
        btnXoa = new javax.swing.JButton();
        pnlBtnMoi = new javax.swing.JPanel();
        btnMoi = new javax.swing.JButton();
        pnlNguoiThuePhong = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        pnlBtnXoa_NguoiThuePhong = new javax.swing.JPanel();
        btnXoa_NguoiThuePhong = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblThanhVien = new javax.swing.JTable();
        lblDaiDien = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        pnlBtnThem_NguoiThuePhong = new javax.swing.JPanel();
        btnThem_NguoiThuePhong = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblThemThanhVien = new javax.swing.JTable();
        pnlDichVuPhong = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();
        pnlBtnXoa_DichVuPhong = new javax.swing.JPanel();
        btnXoa_DichVuPhong = new javax.swing.JButton();
        pnl_ThemDichVu = new javax.swing.JPanel();
        cboDichVu = new javax.swing.JComboBox<>();
        txtSoLuong = new javax.swing.JTextField();
        pnlBtnThem_DichVuPhong = new javax.swing.JPanel();
        btnThemDichVuPhong = new javax.swing.JButton();
        pnlBtnCapNhat_DichVuPhong = new javax.swing.JPanel();
        btnCapNhatDichVu = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblHoaDonChiTiet = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblTenPhong = new javax.swing.JLabel();
        lblTenToaNha = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblSoToaNha2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1030, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        pnlContent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pnlContent.setPreferredSize(new java.awt.Dimension(1010, 660));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tblPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nhà", "Phòng", "Tầng", "Diện tích", "Giá", "Mô tả", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPhong.setGridColor(new java.awt.Color(204, 204, 204));
        tblPhong.setRowHeight(30);
        tblPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPhongMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblPhong);
        if (tblPhong.getColumnModel().getColumnCount() > 0) {
            tblPhong.getColumnModel().getColumn(0).setMinWidth(32);
            tblPhong.getColumnModel().getColumn(0).setPreferredWidth(32);
            tblPhong.getColumnModel().getColumn(0).setMaxWidth(32);
            tblPhong.getColumnModel().getColumn(1).setMinWidth(100);
            tblPhong.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblPhong.getColumnModel().getColumn(1).setMaxWidth(100);
            tblPhong.getColumnModel().getColumn(6).setPreferredWidth(200);
            tblPhong.getColumnModel().getColumn(6).setMaxWidth(500);
        }

        txtTimKiem2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTimKiem2.setBorder(null);

        txtTimKiem.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));

        btnTimKiem2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTimKiem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search_24px.png"))); // NOI18N
        btnTimKiem2.setBorder(null);
        btnTimKiem2.setContentAreaFilled(false);
        btnTimKiem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiem2)
                .addContainerGap(366, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTimKiem2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        cboLoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboLoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nhà" }));
        cboLoc.setBorder(null);

        chkDaThue.setBackground(new java.awt.Color(255, 255, 255));
        chkDaThue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkDaThue.setText("Đã thuê");

        chkChuaThue.setBackground(new java.awt.Color(255, 255, 255));
        chkChuaThue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkChuaThue.setText("Chưa thuê");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Bộ lọc");

        btnApDung.setText("Áp dụng");
        btnApDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApDungActionPerformed(evt);
            }
        });

        jLabel3.setText("Trạng thái:");

        jLabel4.setText("Tòa nhà:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnApDung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboLoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(chkDaThue, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chkChuaThue, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDaThue, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkChuaThue, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnApDung, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimKiem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTimKiem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnlContent.addTab("Danh sách phòng", jPanel5);

        pnlChiTietPhong.setBackground(new java.awt.Color(255, 255, 255));
        pnlChiTietPhong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlNoiDungChiTietPhong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pnlThongTinPhong.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nhà");

        txtPhong.setBorder(null);

        jLabel5.setText("Phòng");

        txtDienTich.setBorder(null);

        jLabel6.setText("Diện tích");

        jLabel7.setText("Giá");

        txtMoTa.setBorder(null);

        jLabel8.setText("Trạng thái");

        jLabel9.setText("Tầng");

        txtTang.setBorder(null);

        jLabel10.setText("Mô tả");

        txtGia.setBorder(null);

        txtTrangThai.setEditable(false);
        txtTrangThai.setBackground(new java.awt.Color(255, 255, 255));
        txtTrangThai.setBorder(null);

        pnlMoTaKhac.setBackground(new java.awt.Color(255, 255, 255));
        pnlMoTaKhac.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mô tả khác", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        pnlMoTaKhac.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chkLoc1.setBackground(new java.awt.Color(255, 255, 255));
        chkLoc1.setText("Có sẵn điều hòa");
        chkLoc1.setToolTipText("DieuHoa");
        pnlMoTaKhac.add(chkLoc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, -1));

        chkLoc6.setBackground(new java.awt.Color(255, 255, 255));
        chkLoc6.setText("Nhà vệ sinh khép kín");
        chkLoc6.setToolTipText("ChoPhoiDoRieng");
        pnlMoTaKhac.add(chkLoc6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        chkLoc7.setBackground(new java.awt.Color(255, 255, 255));
        chkLoc7.setText("Giờ ra vào tự do");
        chkLoc7.setToolTipText("ChoDeXe");
        pnlMoTaKhac.add(chkLoc7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 123, -1));

        chkLoc2.setBackground(new java.awt.Color(255, 255, 255));
        chkLoc2.setText("Có sẵn bình nước nóng lạnh");
        chkLoc2.setToolTipText("DieuHoa");
        chkLoc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLoc2ActionPerformed(evt);
            }
        });
        pnlMoTaKhac.add(chkLoc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        chkLoc3.setBackground(new java.awt.Color(255, 255, 255));
        chkLoc3.setText("Có chỗ để xe");
        chkLoc3.setToolTipText("Camera");
        pnlMoTaKhac.add(chkLoc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 139, -1));

        chkLoc8.setBackground(new java.awt.Color(255, 255, 255));
        chkLoc8.setText("Đồng hồ điện nước riêng");
        chkLoc8.setToolTipText("KhepKin");
        pnlMoTaKhac.add(chkLoc8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        chkLoc9.setBackground(new java.awt.Color(255, 255, 255));
        chkLoc9.setText("Có khu phơi đồ riêng");
        pnlMoTaKhac.add(chkLoc9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        chkLoc4.setBackground(new java.awt.Color(255, 255, 255));
        chkLoc4.setText("Ở chung chủ");
        chkLoc4.setToolTipText("ChungChu");
        pnlMoTaKhac.add(chkLoc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 139, -1));

        chkLoc5.setBackground(new java.awt.Color(255, 255, 255));
        chkLoc5.setText("Được nấu ăn trong phòng");
        chkLoc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLoc5ActionPerformed(evt);
            }
        });
        pnlMoTaKhac.add(chkLoc5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 30));

        pnlButton.setBackground(new java.awt.Color(255, 255, 255));

        pnlThem.setBackground(new java.awt.Color(40, 63, 85));

        btnThem.setBackground(new java.awt.Color(40, 63, 85));
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.setBorder(null);
        btnThem.setBorderPainted(false);
        btnThem.setContentAreaFilled(false);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThemLayout = new javax.swing.GroupLayout(pnlThem);
        pnlThem.setLayout(pnlThemLayout);
        pnlThemLayout.setHorizontalGroup(
            pnlThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlThemLayout.setVerticalGroup(
            pnlThemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThemLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlCapNhat.setBackground(new java.awt.Color(40, 63, 85));

        btnCapNhat.setBackground(new java.awt.Color(40, 63, 85));
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.setBorder(null);
        btnCapNhat.setBorderPainted(false);
        btnCapNhat.setContentAreaFilled(false);
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCapNhatLayout = new javax.swing.GroupLayout(pnlCapNhat);
        pnlCapNhat.setLayout(pnlCapNhatLayout);
        pnlCapNhatLayout.setHorizontalGroup(
            pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCapNhatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlCapNhatLayout.setVerticalGroup(
            pnlCapNhatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlXoa.setBackground(new java.awt.Color(40, 63, 85));

        btnXoa.setBackground(new java.awt.Color(40, 63, 85));
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.setBorderPainted(false);
        btnXoa.setContentAreaFilled(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlXoaLayout = new javax.swing.GroupLayout(pnlXoa);
        pnlXoa.setLayout(pnlXoaLayout);
        pnlXoaLayout.setHorizontalGroup(
            pnlXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlXoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlXoaLayout.setVerticalGroup(
            pnlXoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlBtnMoi.setBackground(new java.awt.Color(40, 63, 85));

        btnMoi.setBackground(new java.awt.Color(40, 63, 85));
        btnMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnMoi.setText("Mới");
        btnMoi.setBorderPainted(false);
        btnMoi.setContentAreaFilled(false);
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnMoiLayout = new javax.swing.GroupLayout(pnlBtnMoi);
        pnlBtnMoi.setLayout(pnlBtnMoiLayout);
        pnlBtnMoiLayout.setHorizontalGroup(
            pnlBtnMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBtnMoiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMoi, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlBtnMoiLayout.setVerticalGroup(
            pnlBtnMoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBtnMoiLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlButtonLayout = new javax.swing.GroupLayout(pnlButton);
        pnlButton.setLayout(pnlButtonLayout);
        pnlButtonLayout.setHorizontalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonLayout.createSequentialGroup()
                .addComponent(pnlThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBtnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlButtonLayout.setVerticalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlThem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlXoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlBtnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout pnlThongTinPhongLayout = new javax.swing.GroupLayout(pnlThongTinPhong);
        pnlThongTinPhong.setLayout(pnlThongTinPhongLayout);
        pnlThongTinPhongLayout.setHorizontalGroup(
            pnlThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinPhongLayout.createSequentialGroup()
                        .addGroup(pnlThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(cboNha, 0, 460, Short.MAX_VALUE)
                            .addComponent(jLabel9)
                            .addComponent(txtTang, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                            .addComponent(jSeparator13, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                            .addComponent(jLabel10)
                            .addComponent(txtMoTa)
                            .addComponent(jSeparator12, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                            .addComponent(pnlMoTaKhac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pnlThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlThongTinPhongLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pnlThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(txtGia, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                                    .addComponent(jSeparator11, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtTrangThai, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                                    .addComponent(jSeparator14, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlThongTinPhongLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pnlThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(pnlThongTinPhongLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(txtPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlThongTinPhongLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(pnlThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlThongTinPhongLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addGroup(pnlThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDienTich, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnlThongTinPhongLayout.setVerticalGroup(
            pnlThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinPhongLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(cboNha, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlThongTinPhongLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(4, 4, 4)
                        .addComponent(txtPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlThongTinPhongLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(4, 4, 4)
                        .addComponent(txtTang, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlThongTinPhongLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(4, 4, 4)
                        .addComponent(txtDienTich, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinPhongLayout.createSequentialGroup()
                        .addGroup(pnlThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlThongTinPhongLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(44, 44, 44))
                            .addComponent(txtMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlMoTaKhac, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(pnlThongTinPhongLayout.createSequentialGroup()
                        .addGroup(pnlThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlThongTinPhongLayout.createSequentialGroup()
                                .addGroup(pnlThongTinPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlThongTinPhongLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(44, 44, 44))
                                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4)
                                .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pnlNoiDungChiTietPhong.addTab("Thông tin phòng", pnlThongTinPhong);

        pnlNguoiThuePhong.setBackground(new java.awt.Color(255, 255, 255));

        pnlBtnXoa_NguoiThuePhong.setBackground(new java.awt.Color(40, 63, 85));
        pnlBtnXoa_NguoiThuePhong.setPreferredSize(new java.awt.Dimension(60, 30));

        btnXoa_NguoiThuePhong.setBackground(new java.awt.Color(40, 63, 85));
        btnXoa_NguoiThuePhong.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa_NguoiThuePhong.setText("Xóa khỏi phòng");
        btnXoa_NguoiThuePhong.setBorderPainted(false);
        btnXoa_NguoiThuePhong.setContentAreaFilled(false);
        btnXoa_NguoiThuePhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_NguoiThuePhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnXoa_NguoiThuePhongLayout = new javax.swing.GroupLayout(pnlBtnXoa_NguoiThuePhong);
        pnlBtnXoa_NguoiThuePhong.setLayout(pnlBtnXoa_NguoiThuePhongLayout);
        pnlBtnXoa_NguoiThuePhongLayout.setHorizontalGroup(
            pnlBtnXoa_NguoiThuePhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnXoa_NguoiThuePhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlBtnXoa_NguoiThuePhongLayout.setVerticalGroup(
            pnlBtnXoa_NguoiThuePhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBtnXoa_NguoiThuePhongLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnXoa_NguoiThuePhong, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tblThanhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Họ tên", "Ngày sinh", "Giới tính", "Quê quán", "Điện thoại", "Email", "CMND", "Ghi chú", "Ngày thuê"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThanhVien.setGridColor(new java.awt.Color(204, 204, 204));
        tblThanhVien.setRowHeight(30);
        jScrollPane2.setViewportView(tblThanhVien);

        lblDaiDien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDaiDien.setText("Đại diện thuê phòng: ");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDaiDien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlBtnXoa_NguoiThuePhong, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlBtnXoa_NguoiThuePhong, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addComponent(lblDaiDien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thành viên", jPanel6);

        pnlBtnThem_NguoiThuePhong.setBackground(new java.awt.Color(40, 63, 85));
        pnlBtnThem_NguoiThuePhong.setPreferredSize(new java.awt.Dimension(60, 30));

        btnThem_NguoiThuePhong.setBackground(new java.awt.Color(40, 63, 85));
        btnThem_NguoiThuePhong.setForeground(new java.awt.Color(255, 255, 255));
        btnThem_NguoiThuePhong.setText("Thêm vào phòng");
        btnThem_NguoiThuePhong.setBorderPainted(false);
        btnThem_NguoiThuePhong.setContentAreaFilled(false);
        btnThem_NguoiThuePhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem_NguoiThuePhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnThem_NguoiThuePhongLayout = new javax.swing.GroupLayout(pnlBtnThem_NguoiThuePhong);
        pnlBtnThem_NguoiThuePhong.setLayout(pnlBtnThem_NguoiThuePhongLayout);
        pnlBtnThem_NguoiThuePhongLayout.setHorizontalGroup(
            pnlBtnThem_NguoiThuePhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnThem_NguoiThuePhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );
        pnlBtnThem_NguoiThuePhongLayout.setVerticalGroup(
            pnlBtnThem_NguoiThuePhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnThem_NguoiThuePhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tblThemThanhVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Họ tên", "Ngày sinh", "Giới tính", "Quê quán", "Điện thoại", "Email", "CMND", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblThemThanhVien.setGridColor(new java.awt.Color(204, 204, 204));
        tblThemThanhVien.setRowHeight(30);
        tblThemThanhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblThemThanhVienMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblThemThanhVien);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlBtnThem_NguoiThuePhong, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlBtnThem_NguoiThuePhong, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thêm thành viên", jPanel7);

        javax.swing.GroupLayout pnlNguoiThuePhongLayout = new javax.swing.GroupLayout(pnlNguoiThuePhong);
        pnlNguoiThuePhong.setLayout(pnlNguoiThuePhongLayout);
        pnlNguoiThuePhongLayout.setHorizontalGroup(
            pnlNguoiThuePhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNguoiThuePhongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        pnlNguoiThuePhongLayout.setVerticalGroup(
            pnlNguoiThuePhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNguoiThuePhongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pnlNoiDungChiTietPhong.addTab("Người thuê phòng", pnlNguoiThuePhong);

        pnlDichVuPhong.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane6.setBorder(javax.swing.BorderFactory.createTitledBorder("Dịch vụ phòng đang sử dụng"));

        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Tên dich vụ", "Đơn giá", "Số lượng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDichVu.setGridColor(new java.awt.Color(204, 204, 204));
        tblDichVu.setRowHeight(30);
        jScrollPane6.setViewportView(tblDichVu);
        if (tblDichVu.getColumnModel().getColumnCount() > 0) {
            tblDichVu.getColumnModel().getColumn(0).setMinWidth(32);
            tblDichVu.getColumnModel().getColumn(0).setPreferredWidth(32);
            tblDichVu.getColumnModel().getColumn(0).setMaxWidth(32);
        }

        pnlBtnXoa_DichVuPhong.setBackground(new java.awt.Color(40, 63, 85));
        pnlBtnXoa_DichVuPhong.setPreferredSize(new java.awt.Dimension(60, 30));

        btnXoa_DichVuPhong.setBackground(new java.awt.Color(40, 63, 85));
        btnXoa_DichVuPhong.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa_DichVuPhong.setText("Xóa dịch vụ");
        btnXoa_DichVuPhong.setBorderPainted(false);
        btnXoa_DichVuPhong.setContentAreaFilled(false);
        btnXoa_DichVuPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa_DichVuPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnXoa_DichVuPhongLayout = new javax.swing.GroupLayout(pnlBtnXoa_DichVuPhong);
        pnlBtnXoa_DichVuPhong.setLayout(pnlBtnXoa_DichVuPhongLayout);
        pnlBtnXoa_DichVuPhongLayout.setHorizontalGroup(
            pnlBtnXoa_DichVuPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnXoa_DichVuPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
        );
        pnlBtnXoa_DichVuPhongLayout.setVerticalGroup(
            pnlBtnXoa_DichVuPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBtnXoa_DichVuPhongLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnXoa_DichVuPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_ThemDichVu.setBorder(javax.swing.BorderFactory.createTitledBorder("Thêm dịch vụ"));

        cboDichVu.setBorder(javax.swing.BorderFactory.createTitledBorder("Dich vụ"));

        txtSoLuong.setBorder(javax.swing.BorderFactory.createTitledBorder("Số lượng"));
        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        pnlBtnThem_DichVuPhong.setBackground(new java.awt.Color(40, 63, 85));
        pnlBtnThem_DichVuPhong.setPreferredSize(new java.awt.Dimension(60, 30));

        btnThemDichVuPhong.setBackground(new java.awt.Color(40, 63, 85));
        btnThemDichVuPhong.setForeground(new java.awt.Color(255, 255, 255));
        btnThemDichVuPhong.setText("Thêm");
        btnThemDichVuPhong.setBorderPainted(false);
        btnThemDichVuPhong.setContentAreaFilled(false);
        btnThemDichVuPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDichVuPhongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnThem_DichVuPhongLayout = new javax.swing.GroupLayout(pnlBtnThem_DichVuPhong);
        pnlBtnThem_DichVuPhong.setLayout(pnlBtnThem_DichVuPhongLayout);
        pnlBtnThem_DichVuPhongLayout.setHorizontalGroup(
            pnlBtnThem_DichVuPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnThemDichVuPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
        );
        pnlBtnThem_DichVuPhongLayout.setVerticalGroup(
            pnlBtnThem_DichVuPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnThemDichVuPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_ThemDichVuLayout = new javax.swing.GroupLayout(pnl_ThemDichVu);
        pnl_ThemDichVu.setLayout(pnl_ThemDichVuLayout);
        pnl_ThemDichVuLayout.setHorizontalGroup(
            pnl_ThemDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ThemDichVuLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(cboDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(pnlBtnThem_DichVuPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_ThemDichVuLayout.setVerticalGroup(
            pnl_ThemDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ThemDichVuLayout.createSequentialGroup()
                .addGroup(pnl_ThemDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlBtnThem_DichVuPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_ThemDichVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cboDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pnlBtnCapNhat_DichVuPhong.setBackground(new java.awt.Color(40, 63, 85));
        pnlBtnCapNhat_DichVuPhong.setPreferredSize(new java.awt.Dimension(60, 30));

        btnCapNhatDichVu.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhatDichVu.setText("Cập nhật");
        btnCapNhatDichVu.setBorderPainted(false);
        btnCapNhatDichVu.setContentAreaFilled(false);
        btnCapNhatDichVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatDichVuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnCapNhat_DichVuPhongLayout = new javax.swing.GroupLayout(pnlBtnCapNhat_DichVuPhong);
        pnlBtnCapNhat_DichVuPhong.setLayout(pnlBtnCapNhat_DichVuPhongLayout);
        pnlBtnCapNhat_DichVuPhongLayout.setHorizontalGroup(
            pnlBtnCapNhat_DichVuPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCapNhatDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlBtnCapNhat_DichVuPhongLayout.setVerticalGroup(
            pnlBtnCapNhat_DichVuPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBtnCapNhat_DichVuPhongLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCapNhatDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout pnlDichVuPhongLayout = new javax.swing.GroupLayout(pnlDichVuPhong);
        pnlDichVuPhong.setLayout(pnlDichVuPhongLayout);
        pnlDichVuPhongLayout.setHorizontalGroup(
            pnlDichVuPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDichVuPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDichVuPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
                    .addGroup(pnlDichVuPhongLayout.createSequentialGroup()
                        .addComponent(pnl_ThemDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnlBtnCapNhat_DichVuPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlBtnXoa_DichVuPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlDichVuPhongLayout.setVerticalGroup(
            pnlDichVuPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDichVuPhongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDichVuPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnl_ThemDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDichVuPhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(pnlBtnCapNhat_DichVuPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlBtnXoa_DichVuPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlNoiDungChiTietPhong.addTab("Dịch vụ phòng", pnlDichVuPhong);

        tblHoaDonChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Khoản thu", "Số cũ", "Số mới", "Giá", "Thành tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDonChiTiet.setGridColor(new java.awt.Color(204, 204, 204));
        tblHoaDonChiTiet.setRowHeight(30);
        jScrollPane5.setViewportView(tblHoaDonChiTiet);

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "IdHoaDon", "Tháng-Năm", "Trạng Thái Hóa Đơn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDon.setGridColor(new java.awt.Color(204, 204, 204));
        tblHoaDon.setRowHeight(30);
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("HÓA ĐƠN");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("HÓA ĐƠN CHI TIẾT");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(198, Short.MAX_VALUE))
        );

        pnlNoiDungChiTietPhong.addTab("Hóa đơn", jPanel8);

        pnlChiTietPhong.add(pnlNoiDungChiTietPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1000, 530));

        lblTenPhong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTenPhong.setText("Phòng:");
        pnlChiTietPhong.add(lblTenPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 130, 30));

        lblTenToaNha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTenToaNha.setText("Nhà: ");
        pnlChiTietPhong.add(lblTenToaNha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        pnlContent.addTab("Chi tiết phòng", pnlChiTietPhong);

        jPanel2.setBackground(new java.awt.Color(40, 63, 85));

        lblSoToaNha2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSoToaNha2.setForeground(new java.awt.Color(255, 255, 255));
        lblSoToaNha2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoToaNha2.setText("Phòng");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSoToaNha2)
                .addContainerGap(924, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSoToaNha2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 651, Short.MAX_VALUE)))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1010, 710));
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoa_NguoiThuePhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa_NguoiThuePhongActionPerformed
        // TODO add your handling code here:
        xoaThanhVien();
    }//GEN-LAST:event_btnXoa_NguoiThuePhongActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        filltotablephongbytimkiem();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPhongMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            pnlContent.setSelectedIndex(1);
            pnlNoiDungChiTietPhong.setSelectedIndex(0);
            index = tblPhong.getSelectedRow();
            edit();
            fillToCboDichVu();
            filltotableDichVuPhong();
        }

    }//GEN-LAST:event_tblPhongMouseClicked

    private void btnApDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApDungActionPerformed
        // TODO add your handling code here:
        fillToTablePhongBFilter();
    }//GEN-LAST:event_btnApDungActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        newForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnThem_NguoiThuePhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem_NguoiThuePhongActionPerformed
        // TODO add your handling code here:
        themthanhvien();
    }//GEN-LAST:event_btnThem_NguoiThuePhongActionPerformed

    private void tblThemThanhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblThemThanhVienMouseClicked
        // TODO add your handling code here:
        index_them = tblThemThanhVien.getSelectedRow();
    }//GEN-LAST:event_tblThemThanhVienMouseClicked

    private void btnXoa_DichVuPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa_DichVuPhongActionPerformed
        // TODO add your handling code here:
        xoaDichVu();
    }//GEN-LAST:event_btnXoa_DichVuPhongActionPerformed

    private void btnThemDichVuPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDichVuPhongActionPerformed
        // TODO add your handling code here:
        themDichVuPhong();
    }//GEN-LAST:event_btnThemDichVuPhongActionPerformed

    private void chkLoc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLoc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkLoc2ActionPerformed

    private void chkLoc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLoc5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkLoc5ActionPerformed

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void btnCapNhatDichVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatDichVuActionPerformed
        // TODO add your handling code here:
        updateDichVuPhong();
    }//GEN-LAST:event_btnCapNhatDichVuActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
        fillToHoaDonChiTiet();
    }//GEN-LAST:event_tblHoaDonMouseClicked

    ToaNhaDao tnDao = new ToaNhaDao();

    public void filltoCbo() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLoc.getModel();
        model.removeAllElements();
        listtoanha = tnDao.selectAll();
        for (ToaNha t : listtoanha) {
            model.addElement(t);
        }
    }
    PhongDao dao = new PhongDao();
    public static String sql = "";

    public void fillToTablePhongBFilter() {
        if (chkDaThue.isSelected() == true && chkChuaThue.isSelected() == false) {
            sql = "select Phong.*, TOA_NHA.TenToaNha from PHONG inner join TOA_NHA on PHONG.IdToaNha = TOA_NHA.IdToaNha where TrangThai = 1 and TOA_NHA.IdToaNha = ?";
        } else if (chkDaThue.isSelected() == false && chkChuaThue.isSelected() == true) {
            sql = "select Phong.*, TOA_NHA.TenToaNha from PHONG inner join TOA_NHA on PHONG.IdToaNha = TOA_NHA.IdToaNha where TrangThai = 0 and TOA_NHA.IdToaNha = ?";
        } else {
            sql = "select Phong.*, TOA_NHA.TenToaNha from PHONG inner join TOA_NHA on PHONG.IdToaNha = TOA_NHA.IdToaNha where TOA_NHA.IdToaNha = ?";
        }
        int idNha = ((ToaNha) cboLoc.getSelectedItem()).getIdtoanha();
        List<Phong> list = dao.selectbyfilter(idNha);
        DefaultTableModel model = (DefaultTableModel) tblPhong.getModel();
        model.setRowCount(0);
        for (Phong p : list) {
            Object[] row = new Object[]{p.getIdphong(), p.getTentoanha(), p.getPhong(), p.getTang(), p.getDientich(), p.getGia(), p.getMota(), p.isTrangthai() == true ? "Đã thuê" : "Chưa thuê"};
            model.addRow(row);
        }
    }

    public void filltotablephongbytimkiem() {
        String name = txtTimKiem.getText();
        List<Phong> list;
        if (Auth.user.isRoles() == false) {
            list = dao.selectbyKhchThue(Auth.user.getIdkhachthue(), name);
        } else {
            list = dao.selectbyname(name);
        }
        DefaultTableModel model = (DefaultTableModel) tblPhong.getModel();
        model.setRowCount(0);
        for (Phong p : list) {
            Object[] row = new Object[]{p.getIdphong(), p.getTentoanha(), p.getPhong(), p.getTang(), p.getDientich(), p.getGia(), p.getMota(), p.isTrangthai() == true ? "Đã thuê" : "Chưa thuê"};
            model.addRow(row);
        }
    }
    List<ToaNha> listtoanha;

    public void filltocboNha() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboNha.getModel();
        model.removeAllElements();
        listtoanha = tnDao.selectAll();
        for (ToaNha t : listtoanha) {
            model.addElement(t);
        }
    }

    public void showDetail(Phong p) {
        System.out.println(p);
        txtPhong.setText(p.getPhong());
        txtTang.setText(p.getTang() + "");
        txtDienTich.setText(p.getDientich() + "");
        txtGia.setText(p.getGia() + "");
        txtMoTa.setText(p.getMota());
        txtTrangThai.setText(p.isTrangthai() == true ? "Đã thuê" : "Chưa thuê");
        String tentoanha = tblPhong.getValueAt(index, 1) + "";
        lblTenToaNha.setText("Tòa nhà: " + tentoanha);
        lblTenPhong.setText("Phòng: " + p.getPhong());

    }
    public int index;
    public int idphong;
    MoTaDao mtDao = new MoTaDao();

    public void edit() {
        idphong = Integer.parseInt(tblPhong.getValueAt(index, 0) + "");
        Phong p = dao.selectByID(idphong);
        showDetail(p);
        setStatus(false);
        fillToThanhVien();
        fillYToThemThanhVien();
        fillToHoaDon();
        MoTa mt = mtDao.setStatus(idphong);
        chkLoc1.setSelected(mt.isLoc1());
        chkLoc2.setSelected(mt.isLoc2());
        chkLoc3.setSelected(mt.isLoc3());
        chkLoc4.setSelected(mt.isLoc4());
        chkLoc5.setSelected(mt.isLoc5());
        chkLoc6.setSelected(mt.isLoc6());
        chkLoc7.setSelected(mt.isLoc7());
        chkLoc8.setSelected(mt.isLoc8());
        chkLoc9.setSelected(mt.isLoc9());

    }

    public boolean validateForm() {
        if (txtPhong.getText().length() == 0 || txtTang.getText().length() == 0 || txtMoTa.getText().length() == 0 || txtDienTich.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "Bạn phải điền đủ thông tin");
            return false;
        }
        try {
            double gia = Double.parseDouble(txtGia.getText());
            if (gia <= 0) {
                JOptionPane.showMessageDialog(this, "Giá không hợp lệ");
                return false;
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá không hợp lệ");
            return false;
        }
        try {
            double dientich = Double.parseDouble(txtDienTich.getText());
            if (dientich <= 0) {
                JOptionPane.showMessageDialog(this, "Diện tích không hợp lệ");
                return false;
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Diện tích không hợp lệ");
            return false;
        }
        return true;
    }

    public void insert() {
        if (validateForm()) {
            dao.insert(getModel());
            filltotablephongbytimkiem();
            MoTa mt = getMoTa();
            idphong = Integer.parseInt(tblPhong.getValueAt(tblPhong.getRowCount() - 1, 0) + "");
            mt.setIdphong(idphong);
            mtDao.insertmota(mt);
            JOptionPane.showMessageDialog(this, "Đã thêm");
            tblPhong.setRowSelectionInterval(tblPhong.getRowCount() - 1, tblPhong.getRowCount() - 1);
            fillYToThemThanhVien();
            fillToThanhVien();
            fillToCboDichVu();
            filltotableDichVuPhong();
            lblTenToaNha.setText("Nhà: " + cboNha.getSelectedItem() + "");
            lblTenPhong.setText("Phòng:" + txtPhong.getText());
        }
    }

    public MoTa getMoTa() {
        MoTa mt = new MoTa(idphong, chkLoc1.isSelected(), chkLoc2.isSelected(), chkLoc3.isSelected(), chkLoc4
                .isSelected(), chkLoc5.isSelected(), chkLoc6.isSelected(), chkLoc7.isSelected(), chkLoc8.isSelected(), chkLoc9.isSelected());
        return mt;
    }

    public Phong getModel() {
        int idToaNha = ((ToaNha) cboNha.getSelectedItem()).getIdtoanha();
        Phong p = new Phong(
                0, txtPhong.getText(), Integer.parseInt(txtTang.getText()), Double.parseDouble(txtDienTich.getText()), Double.parseDouble(txtGia.getText()), txtMoTa.getText(), false, idToaNha, ""
        );
        return p;

    }

    public void update() {
        if (validateForm()) {
            Phong p = getModel();
            idphong = Integer.parseInt(tblPhong.getValueAt(index, 0) + "");
            p.setIdphong(idphong);
            String trangThai = tblPhong.getValueAt(index, 6) + "";
            p.setTrangthai("Đã thuê".equals(trangThai));
            dao.update(p);
            mtDao.updatemota(getMoTa());
            filltotablephongbytimkiem();
            lblTenPhong.setText("Phòng:" + txtPhong.getText());
            JOptionPane.showMessageDialog(this, "Đã cập nhật");
        }

    }

    public void delete() {
        try {
            if (JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa?") == 0) {
                mtDao.deletemota(idphong);
                XJDBC.update("delete from DICH_VU_PHONG where IdPhong = ?", idphong);
                dao.delete(idphong);
                filltotablephongbytimkiem();
                JOptionPane.showMessageDialog(this, "Đã xóa");
                newForm();
            }
        } catch (Exception e) {
            MoTa mt = getMoTa();
            mt.setIdphong(idphong);
            mtDao.insertmota(mt);
            JOptionPane.showMessageDialog(this, "Không thể xóa phòng đang có người thuê");
        }
    }

    public void newForm() {
        txtPhong.setText("");
        txtTang.setText("");
        txtDienTich.setText("");
        txtMoTa.setText("");
        txtMoTa.setText("");
        cboNha.setSelectedIndex(0);
        txtTrangThai.setText("");
        lblTenPhong.setText("");
        lblTenToaNha.setText("");
        setStatus(true);
        chkLoc1.setSelected(false);
        chkLoc2.setSelected(false);
        chkLoc3.setSelected(false);
        chkLoc4.setSelected(false);
        chkLoc5.setSelected(false);
        chkLoc6.setSelected(false);
        chkLoc7.setSelected(false);
        chkLoc8.setSelected(false);
        chkLoc9.setSelected(false);

        modelHDCT = (DefaultTableModel) tblHoaDon.getModel();
        modelHDCT.setRowCount(0);
        modelHoaDon = (DefaultTableModel) tblHoaDonChiTiet.getModel();
        modelHoaDon.setRowCount(0);
    }

    public void setStatus(boolean insertable) {
        btnThem.setEnabled(insertable);
        btnCapNhat.setEnabled(!insertable);
        btnXoa.setEnabled(!insertable);
        cboNha.setEnabled(insertable);
        if (insertable == true) {
            pnlThem.setBackground(colorEnable);
            pnlCapNhat.setBackground(colorDisable);
            pnlXoa.setBackground(colorDisable);
        } else {
            pnlThem.setBackground(colorDisable);
            pnlCapNhat.setBackground(colorEnable);
            pnlXoa.setBackground(colorEnable);
        }
    }
    KhachThueDao kdao = new KhachThueDao();

    public void fillToThanhVien() {
        DefaultTableModel model = (DefaultTableModel) tblThanhVien.getModel();
        model.setRowCount(0);
        List<Object[]> list = kdao.getThanhVien(idphong);
        for (Object[] kh : list) {
            model.addRow(kh);
        }
        try {
            KhachThue k = kdao.selectDaiDien(idphong);
            lblDaiDien.setText("Người đại diện thuê: " + k.getHoTen());
        } catch (Exception e) {
            lblDaiDien.setText("Người đại diện thuê: ");
        }
    }

    public void fillYToThemThanhVien() {
        DefaultTableModel model = (DefaultTableModel) tblThemThanhVien.getModel();
        model.setRowCount(0);
        List<KhachThue> list = kdao.selectThemThanhVien(idphong);
        for (KhachThue kh : list) {
            Object[] row = new Object[]{kh.getIdKhachThue(), kh.getHoTen(), kh.getNgaySinh(), kh.isGioiTinh() == true ? "Nam" : "Nữ",
                kh.getQueQuan(), kh.getDienThoai(), kh.getEmail(), kh.getcMND(), kh.getGhiChu()};
            model.addRow(row);
        }
    }
    int index_them;

    public void themthanhvien() {
        try {
            int idkhachthem = Integer.parseInt(tblThemThanhVien.getValueAt(index_them, 0) + "");
            if (tblThanhVien.getRowCount() == 0) {
                dao.themThanhVien(idkhachthem, idphong, true);
            } else {
                dao.themThanhVien(idkhachthem, idphong, false);
            }
            JOptionPane.showMessageDialog(this, "Đã thêm");
            XJDBC.update("update PHONG set TrangThai = 1 where IdPhong = " + idphong);
            filltotablephongbytimkiem();
            fillToThanhVien();
            fillYToThemThanhVien();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Chọn 1 người để thêm");
        }
    }

    public void xoaThanhVien() {
        int index_xoa = tblThanhVien.getSelectedRow();
        try {
            int idkhachxoa = Integer.parseInt(tblThanhVien.getValueAt(index_xoa, 0) + "");
            if (JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa") == 0) {
                KhachThue kt = kdao.selectDaiDien(idphong);
                dao.xoaThanhVien(idkhachxoa, idphong);
                fillToThanhVien();
                fillYToThemThanhVien();
                JOptionPane.showMessageDialog(this, "Đã xóa");
                if (tblThanhVien.getRowCount() == 0) {
                    System.out.println("true");
                    XJDBC.update("update PHONG set TrangThai = 0 where IdPhong = " + idphong);
                } else {
                    int idDaiDienMoi = Integer.parseInt(tblThanhVien.getValueAt(0, 0) + "");
                    if (idkhachxoa == kt.getIdKhachThue()) {
                        XJDBC.update("UPDATE PHONG_THUE SET VaiTro = 0 WHERE IdPhong = ? and IdKhachThue = ?", idphong, idkhachxoa);
                        XJDBC.update("UPDATE PHONG_THUE SET VaiTro = 1 WHERE IdPhong = ? and IdKhachThue = ?", idphong, idDaiDienMoi);
                    }
                }
                filltotablephongbytimkiem();
                fillToThanhVien();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Chọn thành viên muốn xóa");
        }

    }

    DichVuDao dvdao = new DichVuDao();

    public void fillToCboDichVu() {
        List<DichVu> listdv = dvdao.selectByToaNha_Phong(idphong);
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboDichVu.getModel();
        model.removeAllElements();
        for (DichVu dv : listdv) {
            model.addElement(dv);
        }
        if (listdv.isEmpty()) {
            model.addElement("Đã thêm tất cả các dịch vụ");
        }
    }
    DichVuPhongDao dvpdao = new DichVuPhongDao();

    public void filltotableDichVuPhong() {
        DefaultTableModel model = (DefaultTableModel) tblDichVu.getModel();
        model.setRowCount(0);
        List<DichVuPhong> list = dvpdao.selectByIDPhong(idphong);
        for (DichVuPhong x : list) {
            model.addRow(new Object[]{x.getId(), x.getTenDichVu(), x.getGia(), x.getSoLuong()});
        }
    }

    public void updateDichVuPhong() {
        int rows = tblDichVu.getRowCount();
        for (int i = 0; i <= rows - 1; i++) {
            System.out.println(i);
            int id = Integer.parseInt(tblDichVu.getValueAt(i, 0) + "");
            int soluong = Integer.parseInt(tblDichVu.getValueAt(i, 3) + "");
            System.out.println("id " + id);
            System.out.println("\t index" + i);
            dvpdao.updateDichVuPhong(soluong, id);
        }
        filltotableDichVuPhong();
        fillToCboDichVu();
        JOptionPane.showMessageDialog(this, "Đã cập nhật");
    }

    public void xoaDichVu() {
        try {
            int indexDichVu = tblDichVu.getSelectedRow();
            int id = Integer.parseInt(tblDichVu.getValueAt(indexDichVu, 0) + "");
            XJDBC.update("Delete FROM DICH_VU_PHONG where Id = ?", id);
            JOptionPane.showMessageDialog(this, "Đã xóa");
            filltotableDichVuPhong();
            fillToCboDichVu();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Chọn dịch vụ muốn xóa");
        }
    }

    public void themDichVuPhong() {
        try {
            int iddv = ((DichVu) cboDichVu.getSelectedItem()).getId();
            int soLuong = 0;
            try {
                soLuong = Integer.parseInt(txtSoLuong.getText());
                if (soLuong < 0) {
                    JOptionPane.showMessageDialog(this, "Nhập lại số lượng");
                    return;
                }
            } catch (HeadlessException | NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Nhập lại số lượng");
                return;
            }
            dvpdao.insertDichVuPhong(iddv, soLuong, idphong);
            System.out.println(iddv + "-" + idphong + "-" + soLuong);
            filltotableDichVuPhong();
            fillToCboDichVu();
            JOptionPane.showMessageDialog(this, "Đã thêm");
        } catch (Exception e) {
        }
    }

    HoaDonDao hdDao = new HoaDonDao();

    DefaultTableModel modelHoaDon;

    public void fillToHoaDon() {
        List<HoaDon> list = hdDao.selectByPhong(idphong);
        modelHoaDon = (DefaultTableModel) tblHoaDon.getModel();
        modelHoaDon.setRowCount(0);
        for (HoaDon h : list) {
            Object[] row = new Object[]{h.getIdHoaDon(), h.getThang() + "-" + h.getNam(), h.isTrangThai() == true ? "Đã thanh toán " : "Chưa thanh toán"};
            modelHoaDon.addRow(row);
        }
    }
    HoaDonChiTietDao hdctDao = new HoaDonChiTietDao();

    DefaultTableModel modelHDCT;

    public void fillToHoaDonChiTiet() {
        int idHoaDon = Integer.parseInt(tblHoaDon.getValueAt(tblHoaDon.getSelectedRow(), 0) + "");
        List<HoaDonChiTiet> list = hdctDao.selectByIDHoaDon(idHoaDon);
        modelHDCT = (DefaultTableModel) tblHoaDonChiTiet.getModel();
        modelHDCT.setRowCount(0);
        for (HoaDonChiTiet x : list) {
            Object[] o = new Object[]{x.getKhoanThu(), x.getSoCu(), x.getSoMoi(), x.getSuDung(), x.getGia(), x.getSuDung() * x.getGia()};
            modelHDCT.addRow(o);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApDung;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnCapNhatDichVu;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemDichVuPhong;
    private javax.swing.JButton btnThem_NguoiThuePhong;
    private javax.swing.JButton btnTimKiem2;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoa_DichVuPhong;
    private javax.swing.JButton btnXoa_NguoiThuePhong;
    private javax.swing.JComboBox<String> cboDichVu;
    private javax.swing.JComboBox<String> cboLoc;
    private javax.swing.JComboBox<String> cboNha;
    private javax.swing.JCheckBox chkChuaThue;
    private javax.swing.JCheckBox chkDaThue;
    private javax.swing.JCheckBox chkLoc1;
    private javax.swing.JCheckBox chkLoc2;
    private javax.swing.JCheckBox chkLoc3;
    private javax.swing.JCheckBox chkLoc4;
    private javax.swing.JCheckBox chkLoc5;
    private javax.swing.JCheckBox chkLoc6;
    private javax.swing.JCheckBox chkLoc7;
    private javax.swing.JCheckBox chkLoc8;
    private javax.swing.JCheckBox chkLoc9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblDaiDien;
    private javax.swing.JLabel lblSoToaNha2;
    private javax.swing.JLabel lblTenPhong;
    private javax.swing.JLabel lblTenToaNha;
    private javax.swing.JPanel pnlBtnCapNhat_DichVuPhong;
    private javax.swing.JPanel pnlBtnMoi;
    private javax.swing.JPanel pnlBtnThem_DichVuPhong;
    private javax.swing.JPanel pnlBtnThem_NguoiThuePhong;
    private javax.swing.JPanel pnlBtnXoa_DichVuPhong;
    private javax.swing.JPanel pnlBtnXoa_NguoiThuePhong;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlCapNhat;
    private javax.swing.JPanel pnlChiTietPhong;
    private javax.swing.JTabbedPane pnlContent;
    private javax.swing.JPanel pnlDichVuPhong;
    private javax.swing.JPanel pnlMoTaKhac;
    private javax.swing.JPanel pnlNguoiThuePhong;
    private javax.swing.JTabbedPane pnlNoiDungChiTietPhong;
    private javax.swing.JPanel pnlThem;
    private javax.swing.JPanel pnlThongTinPhong;
    private javax.swing.JPanel pnlXoa;
    private javax.swing.JPanel pnl_ThemDichVu;
    private javax.swing.JTable tblDichVu;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblHoaDonChiTiet;
    public static javax.swing.JTable tblPhong;
    private javax.swing.JTable tblThanhVien;
    private javax.swing.JTable tblThemThanhVien;
    private javax.swing.JTextField txtDienTich;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMoTa;
    private javax.swing.JTextField txtPhong;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTang;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtTimKiem2;
    private javax.swing.JTextField txtTrangThai;
    // End of variables declaration//GEN-END:variables
}
