/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.InFoDao;
import dao.PhongDao;
import dao.SuCoDao;
import helper.Auth;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Info;
import model.Phong;
import model.SuCo;

/**
 *
 * @author Admin
 */
public final class SuCoWindows extends javax.swing.JPanel {

    SuCoDao suCoDao = new SuCoDao();
    InFoDao infoDao = new InFoDao();
    List<SuCo> list = new ArrayList<>();
    DefaultTableModel model;
    Info info;
    int index = 0;
    int id = 0;

    /**
     * Creates new form Nha
     */
    public SuCoWindows() {
        initComponents();
        fillToTableSuCo();
        fillToTableDaKhacPhuc();
        if(Auth.user.isRoles() == false) {
            pnlContent.remove(0);
            pnlContent.remove(0);
            filltocbophong();
        }
        else{
            pnlContent.remove(2);
        }
    }

    public boolean check() {
        if (txtTomTatSuCo.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Khong duoc de trong thong tin");
            return false;
        }
        return true;
    }

    public void fillToTableSuCo() {
        model = (DefaultTableModel) tblSuCo.getModel();
        model.setRowCount(0);
        List<SuCo> listSuCo = suCoDao.selectFalse();
        for (SuCo suCoList : listSuCo) {
            model.addRow(new Object[]{suCoList.getIdsuco(), suCoList.getMota(), suCoList.getNha(), suCoList.getPhong(), suCoList.getNguoibao(), suCoList.getNgaybao(), suCoList.getGhichu()});
        }
    }

    public void fillToTableDaKhacPhuc() {
        model = (DefaultTableModel) tblDaKhacPhuc.getModel();
        model.setRowCount(0);
        List<SuCo> listSuCo = suCoDao.selectTrue();
        for (SuCo suCoList : listSuCo) {
            model.addRow(new Object[]{suCoList.getIdsuco(), suCoList.getMota(), suCoList.getNha(), suCoList.getPhong(), suCoList.getNguoibao(), suCoList.getNgaybao(), suCoList.getGhichu()});
        }
    }

    public SuCo getModel() {
        info = Auth.info;
        SuCo sc = new SuCo();
        sc.setMota(txtTomTatSuCo.getText());
        sc.setNha(((Phong)cboPhong.getSelectedItem()).getTentoanha());
        sc.setPhong(((Phong)cboPhong.getSelectedItem()).getPhong());
        sc.setNguoibao(info.getHovaten());
        sc.setNgaybao(String.valueOf(java.time.LocalDate.now()));
        sc.setGhichu(txtChiTiet.getText());
        sc.setTrangthai(false);
        return sc;
    }

    public void themSuCo() {
        SuCo suCo = getModel();
        if (check()) {
            suCoDao.insert(suCo);
            fillToTableSuCo();
            JOptionPane.showMessageDialog(this, "Da bao su co");
            pnlContent.setSelectedIndex(0);
        }
    }

    public void daKhacPhuc() {
        id = (int) tblSuCo.getValueAt(index, 0);
        suCoDao.updateSuCo(id);
        fillToTableSuCo();
        fillToTableDaKhacPhuc();
        pnlContent.setSelectedIndex(1);
    }

    PhongDao pdao = new PhongDao();
    public void filltocbophong() {
        List<Phong> list = pdao.selectbyKhchThue(Auth.user.getIdkhachthue(), "");
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboPhong.getModel();
        model.removeAllElements();
        
        for(Phong p : list) {
            model.addElement(p);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContent = new javax.swing.JTabbedPane();
        pnlSuCo = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSuCo = new javax.swing.JTable();
        pnlBtnDaKhacPhuc = new javax.swing.JPanel();
        btnDaKhacPhuc = new javax.swing.JButton();
        pnlDaKhacPhuc = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblDaKhacPhuc = new javax.swing.JTable();
        btnDaKhacPhuc1 = new javax.swing.JButton();
        pnlBaoCaoSuCo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtTomTatSuCo = new javax.swing.JTextField();
        lblTomTatSuCo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblMoTaSuCo = new javax.swing.JLabel();
        scrChiTiet = new javax.swing.JScrollPane();
        txtChiTiet = new javax.swing.JTextArea();
        pnlBaoSuCo = new javax.swing.JPanel();
        btnBaoSuCo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cboPhong = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        lblSoToaNha3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1030, 710));

        pnlContent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        pnlSuCo.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tblSuCo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Mô tả", "Nhà", "Phòng", "Người báo", "Ngày báo", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSuCo.setGridColor(new java.awt.Color(204, 204, 204));
        tblSuCo.setRowHeight(30);
        tblSuCo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSuCoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblSuCo);

        pnlBtnDaKhacPhuc.setBackground(new java.awt.Color(40, 63, 85));
        pnlBtnDaKhacPhuc.setPreferredSize(new java.awt.Dimension(60, 30));

        btnDaKhacPhuc.setBackground(new java.awt.Color(40, 63, 85));
        btnDaKhacPhuc.setForeground(new java.awt.Color(255, 255, 255));
        btnDaKhacPhuc.setText("Đã khắc phục");
        btnDaKhacPhuc.setBorderPainted(false);
        btnDaKhacPhuc.setContentAreaFilled(false);
        btnDaKhacPhuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaKhacPhucActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBtnDaKhacPhucLayout = new javax.swing.GroupLayout(pnlBtnDaKhacPhuc);
        pnlBtnDaKhacPhuc.setLayout(pnlBtnDaKhacPhucLayout);
        pnlBtnDaKhacPhucLayout.setHorizontalGroup(
            pnlBtnDaKhacPhucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBtnDaKhacPhucLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(btnDaKhacPhuc, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
        );
        pnlBtnDaKhacPhucLayout.setVerticalGroup(
            pnlBtnDaKhacPhucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBtnDaKhacPhucLayout.createSequentialGroup()
                .addComponent(btnDaKhacPhuc, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout pnlSuCoLayout = new javax.swing.GroupLayout(pnlSuCo);
        pnlSuCo.setLayout(pnlSuCoLayout);
        pnlSuCoLayout.setHorizontalGroup(
            pnlSuCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuCoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSuCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 981, Short.MAX_VALUE)
                    .addGroup(pnlSuCoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlBtnDaKhacPhuc, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlSuCoLayout.setVerticalGroup(
            pnlSuCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuCoLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(pnlBtnDaKhacPhuc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlContent.addTab("Sự cố", pnlSuCo);

        pnlDaKhacPhuc.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tblDaKhacPhuc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Mô tả", "Nhà", "Phòng", "Người báo", "Ngày báo", "Ghi chú"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDaKhacPhuc.setGridColor(new java.awt.Color(204, 204, 204));
        tblDaKhacPhuc.setRowHeight(30);
        jScrollPane5.setViewportView(tblDaKhacPhuc);

        btnDaKhacPhuc1.setBackground(new java.awt.Color(255, 255, 255));
        btnDaKhacPhuc1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDaKhacPhuc1.setForeground(new java.awt.Color(40, 63, 85));
        btnDaKhacPhuc1.setText("Lịch sử sự cố");
        btnDaKhacPhuc1.setBorderPainted(false);
        btnDaKhacPhuc1.setContentAreaFilled(false);
        btnDaKhacPhuc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaKhacPhuc1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDaKhacPhucLayout = new javax.swing.GroupLayout(pnlDaKhacPhuc);
        pnlDaKhacPhuc.setLayout(pnlDaKhacPhucLayout);
        pnlDaKhacPhucLayout.setHorizontalGroup(
            pnlDaKhacPhucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDaKhacPhucLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDaKhacPhucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 985, Short.MAX_VALUE)
                    .addGroup(pnlDaKhacPhucLayout.createSequentialGroup()
                        .addComponent(btnDaKhacPhuc1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlDaKhacPhucLayout.setVerticalGroup(
            pnlDaKhacPhucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDaKhacPhucLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDaKhacPhuc1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE))
        );

        pnlContent.addTab("Đã khắc phục", pnlDaKhacPhuc);

        pnlBaoCaoSuCo.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 1, true));

        txtTomTatSuCo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTomTatSuCo.setText("Mất điện");
        txtTomTatSuCo.setBorder(null);

        lblTomTatSuCo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTomTatSuCo.setText("Mô tả");

        lblMoTaSuCo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMoTaSuCo.setText("Ghi chú");

        txtChiTiet.setColumns(20);
        txtChiTiet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtChiTiet.setRows(5);
        txtChiTiet.setText("Phòng 101 mất nước từ 20/11");
        scrChiTiet.setViewportView(txtChiTiet);

        pnlBaoSuCo.setBackground(new java.awt.Color(40, 63, 85));
        pnlBaoSuCo.setPreferredSize(new java.awt.Dimension(60, 30));

        btnBaoSuCo.setBackground(new java.awt.Color(40, 63, 85));
        btnBaoSuCo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBaoSuCo.setForeground(new java.awt.Color(255, 255, 255));
        btnBaoSuCo.setText("Báo sự cố");
        btnBaoSuCo.setBorderPainted(false);
        btnBaoSuCo.setContentAreaFilled(false);
        btnBaoSuCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaoSuCoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBaoSuCoLayout = new javax.swing.GroupLayout(pnlBaoSuCo);
        pnlBaoSuCo.setLayout(pnlBaoSuCoLayout);
        pnlBaoSuCoLayout.setHorizontalGroup(
            pnlBaoSuCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBaoSuCo, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
        );
        pnlBaoSuCoLayout.setVerticalGroup(
            pnlBaoSuCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBaoSuCo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Phòng có sự cố");

        cboPhong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phòng" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addComponent(scrChiTiet)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMoTaSuCo)
                            .addComponent(pnlBaoSuCo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTomTatSuCo, javax.swing.GroupLayout.PREFERRED_SIZE, 951, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTomTatSuCo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboPhong, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(lblTomTatSuCo)
                .addGap(7, 7, 7)
                .addComponent(txtTomTatSuCo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMoTaSuCo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlBaoSuCo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlBaoCaoSuCoLayout = new javax.swing.GroupLayout(pnlBaoCaoSuCo);
        pnlBaoCaoSuCo.setLayout(pnlBaoCaoSuCoLayout);
        pnlBaoCaoSuCoLayout.setHorizontalGroup(
            pnlBaoCaoSuCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaoCaoSuCoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlBaoCaoSuCoLayout.setVerticalGroup(
            pnlBaoCaoSuCoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaoCaoSuCoLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );

        pnlContent.addTab("Báo cáo sự cố", pnlBaoCaoSuCo);

        jPanel4.setBackground(new java.awt.Color(40, 63, 85));

        lblSoToaNha3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSoToaNha3.setForeground(new java.awt.Color(255, 255, 255));
        lblSoToaNha3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoToaNha3.setText("Sự cố");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSoToaNha3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSoToaNha3, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlContent, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBaoSuCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaoSuCoActionPerformed
        themSuCo();
    }//GEN-LAST:event_btnBaoSuCoActionPerformed

    private void btnDaKhacPhucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaKhacPhucActionPerformed
        daKhacPhuc();
    }//GEN-LAST:event_btnDaKhacPhucActionPerformed

    private void tblSuCoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSuCoMouseClicked
        index = tblSuCo.getSelectedRow();
    }//GEN-LAST:event_tblSuCoMouseClicked

    private void btnDaKhacPhuc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaKhacPhuc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDaKhacPhuc1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaoSuCo;
    private javax.swing.JButton btnDaKhacPhuc;
    private javax.swing.JButton btnDaKhacPhuc1;
    private javax.swing.JComboBox<String> cboPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblMoTaSuCo;
    private javax.swing.JLabel lblSoToaNha3;
    private javax.swing.JLabel lblTomTatSuCo;
    private javax.swing.JPanel pnlBaoCaoSuCo;
    private javax.swing.JPanel pnlBaoSuCo;
    private javax.swing.JPanel pnlBtnDaKhacPhuc;
    private javax.swing.JTabbedPane pnlContent;
    private javax.swing.JPanel pnlDaKhacPhuc;
    private javax.swing.JPanel pnlSuCo;
    private javax.swing.JScrollPane scrChiTiet;
    private javax.swing.JTable tblDaKhacPhuc;
    private javax.swing.JTable tblSuCo;
    private javax.swing.JTextArea txtChiTiet;
    private javax.swing.JTextField txtTomTatSuCo;
    // End of variables declaration//GEN-END:variables
}
