/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.ThuChiDao;
import java.awt.BorderLayout;
import java.awt.Color;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Admin
 */
public class ThuChi extends javax.swing.JPanel {

    /**
     * Creates new form ThuChi
     */
    public ThuChi() {
        initComponents();
        cboNam.setSelectedIndex(1);
        cboNam.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblSoToaNha2 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        cboNam = new javax.swing.JComboBox<>();

        jPanel2.setBackground(new java.awt.Color(40, 63, 85));

        lblSoToaNha2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblSoToaNha2.setForeground(new java.awt.Color(255, 255, 255));
        lblSoToaNha2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSoToaNha2.setText("Khoản thu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSoToaNha2)
                .addContainerGap(909, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSoToaNha2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        panel.setLayout(new java.awt.BorderLayout());

        cboNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030" }));
        cboNam.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboNamItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboNam, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 930, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboNam, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboNamItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboNamItemStateChanged
        // TODO add your handling code here:
        setData();
    }//GEN-LAST:event_cboNamItemStateChanged
    ThuChiDao dao = new ThuChiDao();
    public void setData() {
        int nam = Integer.parseInt(cboNam.getSelectedItem().toString());
        int thang_1 = dao.selectbythangnam(1, nam).getTongtien()/10;
        int thang_2 = dao.selectbythangnam(2, nam).getTongtien()/10;
        int thang_3 = dao.selectbythangnam(3, nam).getTongtien()/10;
        int thang_4 = dao.selectbythangnam(4, nam).getTongtien()/10;
        int thang_5 = dao.selectbythangnam(5, nam).getTongtien()/10;
        int thang_6 = dao.selectbythangnam(6, nam).getTongtien()/10;
        int thang_7 = dao.selectbythangnam(7, nam).getTongtien()/10;
        int thang_8 = dao.selectbythangnam(8, nam).getTongtien()/10;
        int thang_9 = dao.selectbythangnam(9, nam).getTongtien()/10;
        int thang_10 = dao.selectbythangnam(10, nam).getTongtien()/10;
        int thang_11 = dao.selectbythangnam(11, nam).getTongtien()/10;
        int thang_12 = dao.selectbythangnam(12, nam).getTongtien()/10;
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(thang_1, "", "Tháng 1");
        dataset.setValue(thang_2, "", "Tháng 2");
        dataset.setValue(thang_3, "", "Tháng 3");
        dataset.setValue(thang_4, "", "Tháng 4");
        dataset.setValue(thang_5, "", "Tháng 5");
        dataset.setValue(thang_6, "", "Tháng 6");
        dataset.setValue(thang_7, "", "Tháng 7");
        dataset.setValue(thang_8, "", "Tháng 8");
        dataset.setValue(thang_9, "", "Tháng 9");
        dataset.setValue(thang_10, "", "Tháng 10");
        dataset.setValue(thang_11, "", "Tháng 11");
        dataset.setValue(thang_12, "", "Tháng 12");

        JFreeChart chart = ChartFactory.createBarChart3D("Khoản thu năm " + nam, "", "", dataset, PlotOrientation.HORIZONTAL, false, false, false);
        CategoryPlot catPlot = chart.getCategoryPlot();
        catPlot.setRangeGridlinePaint(Color.BLACK);
        
        ChartPanel chartPanel = new ChartPanel(chart);
        panel.removeAll();
        panel.add(chartPanel, BorderLayout.CENTER);
        panel.validate();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboNam;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblSoToaNha2;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
